### ISSUE TITLE
Docker: Really slow DVD ripping

### ISSUE THREAD

**Issue by marcusds** [1337-server/automatic-ripping-machine#104]
Is it too be expected to rip six 30 minute episodes off of a DVD to take 4+ hours in docker?

I noticed the log says my hardware is:
```[03:19:05] CPU: Intel(R) Core(TM) i5-6500T CPU @ 2.50GHz
[03:19:05]  - Intel microarchitecture Skylake
[03:19:05]  - logical processor count: 4
[03:19:05] Intel Quick Sync Video support: no
```

Is it because QSV isn't working? My CPU has QSV, and it works in another Docker container I am running.

log: [E1616_164247586768.log](https://github.com/1337-server/automatic-ripping-machine/files/7886931/E1616_164247586768.log)

**Comment by 1337-server** [comment]
The docker image on dockerhub doesn't include Quicksync support. You can rebuild the image yourself if you want to include QS support.

As for the time it takes, you could try changing `ripmethod: backup` to `ripmethod: mkv` this helps for me personally, but it may not help.
