### ISSUE TITLE
[Docker] How do I update the MakeMKV key?

### ISSUE THREAD

**Issue by shitwolfymakes** [1337-server/automatic-ripping-machine#105]
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
Finally had some time to set this up on my new box. Took me a couple days of tinkering but I've got it recognizing disks and running properly.

I tried to run the docker image (`1337server/automatic-ripping-machine:latest`) and got the following message in the failed rip's log:
```
MSG:5021,131332,1,"This application version is too old.  Please download the latest version at http://www.makemkv.com/ or enter a registration key to continue using the current version.","This application version is too old.  Please download the latest version at %1 or enter a registration key to continue using the current version.","http://www.makemkv.com/"
[18-01-2022 17:59:23] ERROR ARM: MakeMKV version is too old.  Upgrade and try again.  MakeMKV returncode is '253'.
[18-01-2022 17:59:23] ERROR ARM: A fatal error has occurred and ARM is exiting.  See traceback below for details.
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 505, in <module>
    main(logfile, job)
  File "/opt/arm/arm/ripper/main.py", line 330, in main
    mkvoutpath = makemkv.makemkv(logfile, job)
  File "/opt/arm/arm/ripper/makemkv.py", line 90, in makemkv
    raise RuntimeError(err)
RuntimeError: MakeMKV version is too old.  Upgrade and try again.  MakeMKV returncode is '253'.
```

I feel like there should be an arm setting that will allow for entering the updated beta key from the web interface. Any ideas?

**Comment by shitwolfymakes** [comment]
Update: managed to build an updated docker image and pushed it to [DockerHub](https://hub.docker.com/r/shitwolfymakes/automatic-ripping-machine). I'm going to try to set up a GitHub action to automate this.

**Comment by 1337-server** [comment]
Sorry about this. Its MakeMKV being out of date on the dockerhub image. Ill need to push the new image.

**Comment by shitwolfymakes** [comment]
Is there anyway to manually update the key? Or does the docker image not store the key stored in the persistent config file?

I'm also currently working on updating the docker branch to the current release. Once that's done, in theory they should have identical functionality and the docker branch could become the new main branch. The only difference should be an extra GitHub Action building the container and pushing it to dockerhub upon release.

I meant to do all this 10 months ago when I first started contributing, but life got in the way 😂

**Comment by 1337-server** [comment]
Sorry, I thought I already replied.

The github actions would be great, as doing things manually now that dockerhub has removed the autobuild is a pain.
