### ISSUE TITLE
Request: Docker image - Text editor

### ISSUE THREAD

**Issue by BarryHuffman** [1337-server/automatic-ripping-machine#109]
**Is your feature request related to a problem? Please describe.**

Not a problem but to simplify editing text files inside the container a minimal text editor could be included.

The existing options of text manipulation is limited to juggling various posix/unix-like utilities, namely: `sed` `tr` `awk` `cat` `echo`  `nl` `sort` `cut`  `head` `tail`  `grep` `find` `more` while there's more my experience is already stretched.

**Describe the solution you'd like**

Including a minimal text editor in the default docker image. 
I'd suggest vi/vim or nano/pico as it's common for headless systems.

**Describe alternatives you've considered**

I've considered alternatives but most require learning curves or are niche, and not included in common repos so I'm appealing broadly.

**Additional context**

(This is merely a suggestion, and may be closed)

**Comment by shitwolfymakes** [comment]
The base image used is ubuntu:20.04, so a text editor should already be included. Are you sure you are attaching to the container properly?

**Comment by BarryHuffman** [comment]
By attaching do you mean with docker exec? 

I'm using `docker exec -it arm-ripper /bin/sh` with the prebuilt dockerhub image `fb19fb2e0514`.

I did a fresh setup with `podman run` using the [template](https://github.com/1337-server/automatic-ripping-machine/wiki/docker). 

Inside the container `apt list --installed` isn't showing nano/vi/vim, and I didn't see either binaries inside `/usr/bin/` or `/usr/sbin/` as `root` or `arm` users.  

(I'm using Fedora as my host system with `dnf` so there's no confusion about package management.)

**Comment by shitwolfymakes** [comment]
Gotcha. I guess that image doesn't come with the full tooling. I'll make a PR to add an install for `nano` to the Dockerfile

**Comment by BarryHuffman** [comment]
Thanks!

For others who need editing currently without much experience, manually copying the file locally, and back from the host is another option. 

# Copy from container to host's pwd

`docker cp arm-rippers:/location/of/file.conf ./file.conf`

# Copy from host to container's path

`docker cp ./file.conf arm-rippers:/location/of/file.conf`

**Comment by shitwolfymakes** [comment]
Don't close this issue just yet! Standard practice is to close it when the PR is merged.

**Comment by BarryHuffman** [comment]
My mistake!

**Comment by 1337-server** [comment]
Closing as this change is now merged. 

Ill need to find a github action to push the new changes to dockerhub

Thanks for your work on this!
