### ISSUE TITLE
Add UI field for updating MakeMKV key

### ISSUE THREAD

**Issue by charmarkk** [1337-server/automatic-ripping-machine#113]
**Is your feature request related to a problem? Please describe.**
It can be difficult to easily update the MakeMKV key (particularly on mobile with no access to a terminal) or intimidating if people aren't used to things yet.

**Describe the solution you'd like**
Adding a field in the UI to update the /../settings.conf would be awesome!

**Are you able to help code/implement this feature ?**
Maybe -- i think a lot of this is done with Python. I'd have to learn that again. Doing HTML work is a bit easier for me.

**Comment by shitwolfymakes** [comment]
Another way to deal with this in the mean time might be to create a cron job that installs the latest version of MakeMKV on the first of every month. But that's not possible if you're using the Docker container.

**Comment by charmarkk** [comment]
Awesome addition @shitwolfymakes! :)

**Comment by shitwolfymakes** [comment]
Thanks!
