### ISSUE TITLE
Is there a way to transcode Blurays in raw folder manually

### ISSUE THREAD

**Issue by gusman80** [1337-server/automatic-ripping-machine#117]
Hi, I chose to keep raw files to try multiple handbrake presets. How can i manually force arm to do the transcoding of raw files and skip the ripping job upfront?

great project, thx!

**Comment by 1337-server** [comment]
It wouldn't be the best option to use ARM in this case. It's much easier to use HandBrake directly.

Full info can be found here. https://handbrake.fr/docs/en/latest/cli/command-line-reference.html If you have access to the GUI version of HandBrake you could also use that.
