### ISSUE TITLE
Error in optional .abcde.conf mungefilename () variation

### ISSUE THREAD

**Issue by mg-man** [1337-server/automatic-ripping-machine#119]
- [ x] I have checked the wiki
- [ x] I have searched for similar issues

**Describe the bug**
There is an error in one of the optional .abcde.conf mungefilename () variations [from Line 512]

**Original** 
 
\# VARIANT 2: (legible style)
\#
\# Accept all chars, EXCEPT '/' (obvious) or ":" (because eyeD3 cannot
\# cope with ":" in pathnames): replace them with " " (space).
\# Additionally, replace contiguous spaces with one space; strip
\# leading spaces; strip trailing spaces and recode to flat filenames.
\#
\#mungefilename ()
\#{
\#	echo "$@" |	sed "s/[:\/]/ /g" | \\
\# 			sed 's/ [ ]*/ /g' | \\
\# 			sed 's/^ *//' | \\
\# 			sed 's/ *$//' | \\
\#}

The last "| \\" causes the config parsing to abort.  Removing the last "| \\" resolves the issue.

FWIW, I've also changed the initial sed command to substitute '-' instead of ' ' when a '/' or ':' is encountered.  Here is the corrected mungefilename I'm using... 

mungefilename ()
{
 	echo "$@" |	sed "s/[:\/]/-/g" | \\
 			sed 's/ [ ]*/ /g' | \\
 			sed 's/^ *//' | \\
 			sed 's/ *$//'
}

### Environment
[Ubuntu 18.04.6 LTS]
[v2_ubuntu18, but probably also all branches]

**Comment by 1337-server** [comment]
Would you be ok with opening a PR ? If not, let me know, and I can do these changes myself.

Thanks!

**Comment by mg-man** [comment]
I'm afriad I'm a GitHub noob... so I'm a bit concerned I might mess something up.  I suppose since I'm on a 'branch' already, that wouldn't be so risky?  Is there somewhere I can read up on the proper way to do a PR?

**Comment by 1337-server** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

This should help. If not, or if you are still unsure, just let me know, and I can merge it.

**Comment by mg-man** [comment]
Hiya... since I'm still pretty green w/r/t GitHub... *and* (more importantly), I'm now back running after a >2yr hiatus due to a broken A.R.M., and with ~100 CDs and DVDs still to rip... if you don't mind, could you make this fix?  Once I'm through the rest of my collection, I'll be updating my A.R.M. to Ubuntu 20.4 and will have another look at contributing - I'm sure there are still some kinks that need ironing out.  

Thanks for all your effort on this!

**Comment by 1337-server** [comment]
This should now be fixed. Thanks
