### ISSUE TITLE
Question about Docker

### ISSUE THREAD

**Issue by Iam2smart** [1337-server/automatic-ripping-machine#12]
Could you make a pre-compiled docker image I want to try using it on unraid but I don’t know we’re to begin.

**Comment by 1337-server** [comment]
This is the pre compiled image.

https://hub.docker.com/r/1337server/automatic-ripping-machine

**Comment by 1337-server** [comment]
I have updated the wiki to try and make things more clear.

https://github.com/1337-server/automatic-ripping-machine/wiki/docker

**Comment by Iam2smart** [comment]
Ok thank you I’ll come back if I have anymore questions
