### ISSUE TITLE
DVD ripping - Task 2 (transcoding) reading from DVD not HD

### ISSUE THREAD

**Issue by mg-man** [1337-server/automatic-ripping-machine#120]
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
When ripping a DVD, the second Task (transcoding) is reading from the DVD, not the HD.  This slows down ripping significantly - about 1 1/2 hours per DVD, tieing up my DVD drives...  FWIW, I think this started happening in the old v2 or v2.1 branch from the original ARM repo - but by the time I'd hit it, I'd already ripped most of my DVDs.  Could this be Ubuntu 18.04 related?

### Environment
[Ubuntu 18.04.6 LTS]
[v2_ubuntu18] 

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[LITTLE_FOCKERS_164591228787.log](https://github.com/1337-server/automatic-ripping-machine/files/8147776/LITTLE_FOCKERS_164591228787.log)

**Comment by mg-man** [comment]
Been researching this... and it doesn't look like Handbrake has an equivalent 'backup' option, and, MakeMKV doesn't appear to support 'backup' for DVDs... Found a discussion about the latter where the following was mentioned as an option...
- https://forum.makemkv.com/forum/viewtopic.php?p=84714#p84714

In linux its very very easy to make an encrypted backup of a DVD

1) install libdvdcss
2) run lsdvd <dvd device> # uses libdvdcss to authenticate the disc ot the drive, without doing this, will get many read failures
3) ddrescue <dev device> test.iso test.log

this will write out the image to test.iso and if any invalid blocks will mark them in test.log for future attempts

Would it be possible to incorporate ddrescue into ARM when ripping DVDs?  The logic would be something like...  

IF media = DVD
  and IF method = backup
     ddrescue <DVD dev> /home/arm/media/raw/movie/'dvd title'.iso
     point Handbrake at the ISO
  elseif 
     'do what happens now'

perhaps someone can add the 'enhancement' label?

**Comment by mg-man** [comment]
FWIW... just used ddrescue to manually 'rip' a DVD... took just over 17mins...

**Comment by mg-man** [comment]
Update... I just ran a manual HandBrakeCLI on the ISO created with ddrescue, and it completed in about 45 mins.  So... the end to end time is about the same (a DVD rip with nothing else running in my machine takes about 1 1/2 hrs)... but... the big gain is that the DVD drive is only tied up for a fraction of the time using this method = multiple DVDs can be loaded and 'queued' up (I have 2 x drives on my ARM...  I'll experiment some with main.py, but I'm NO coder, so it'd be awesome if one of the contributors would consider adding this as a 'backup' method for DVDs...

**Comment by 1337-server** [comment]
Instead of using the backup option, ignore the warning of MakeMKV not being used for dvd's. And change `RIPMETHOD: "backup" ` `RIPMETHOD: "mkv" `

Also, make sure mainfeature is turned off. MakeMKV will not be used to rip the DVD to HDD/SSD and things should be a lot quicker. Hope this helps.

**Comment by mg-man** [comment]
Yes, that seems to work.  I guess I was using this method back on the original v1.x.  Probably worth updating the Wiki / docs since - as you say - MakeMKV is indeed used for the 'first' (Ripping) stage...  Do you want to close this as 'documentation'?

**Comment by 1337-server** [comment]
Yeah, I will close this now.

Thanks!
