### ISSUE TITLE
parse_yaml causes auto run to break

### ISSUE THREAD

**Issue by 1337-server** [1337-server/automatic-ripping-machine#124]
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
ARM on Latest version of OMV (Open media vault) arm_wrapper.sh `parse_yaml` causes auto run to break.

**To Reproduce**
1. Install latest OMV
2. Install ARM
3. Autorun no longer works while parse_yaml function is in the arm_wrapper.sh

### Environment
Debian 10.11 (Buster) - OMV
ARM - v2.6.0

### Log file
N/A

**Comment by 1337-server** [comment]
I have updated the wiki, and the Debian scripts, but I also forgot that my arm.yaml isn't in the standard place. That was the reason for the original error.

**Comment by shitwolfymakes** [comment]
Ah, well two birds with one stone!
