### ISSUE TITLE
Job errors/failure reason isn't tracked

### ISSUE THREAD

**Issue by 1337-server** [1337-server/automatic-ripping-machine#126]
**Is your feature request related to a problem? Please describe.**
When a job fails, ARM doesn't track the reason even though the database has the job.errors entry

**Describe the solution you'd like**
When ARM raises an error or the job fails, update the current job with the correct error/failure reason

**Describe alternatives you've considered**
N/A

**Are you able to help code/implement this feature ?**
Yes/No

**Additional context**

**Comment by shitwolfymakes** [comment]
Please see [this](https://github.com/1337-server/automatic-ripping-machine/issues/136#issuecomment-1082260049) comment

**Comment by 1337-server** [comment]
This is tagged as docker because it affects both branches. But as you are working on the docker version, I haven't worked on the docker branch. It's more to keep track of issues with the devel branch
