### ISSUE TITLE
New formatting of logging causes issues Handbrake & DVDs

### ISSUE THREAD

**Issue by 1337-server** [1337-server/automatic-ripping-machine#128]
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
DVD ripping with fresh installation of Debian 11 and latest commit, causes ARM to crash when it reaches HandBrake

**To Reproduce**
1. Install Debian
2. Install ARM
3. Run ARM with default settings

### Environment
[Debian 11]
[v2.6.0]

### Log file

```
Traceback (most recent call last):
  File "/opt/arm/arm/ripper/main.py", line 462, in <module>
    main(logfile, job)
  File "/opt/arm/arm/ripper/main.py", line 299, in main
    handbrake.handbrake_all(hb_in_path, hb_out_path, logfile, job)
  File "/opt/arm/arm/ripper/handbrake.py", line 117, in handbrake_all
    get_track_info(srcpath, job)
  File "/opt/arm/arm/ripper/handbrake.py", line 303, in get_track_info
    utils.put_track(job, t_no, seconds, aspect, fps, mainfeature, "handbrake")
  File "/opt/arm/arm/ripper/utils.py", line 423, in put_track
    f"Track #{t_no:02} Length: {seconds: >4} fps: {fps:2.3f} "
ValueError: '=' alignment not allowed in string format specifier
```

**Comment by shitwolfymakes** [comment]
What version of python are you using? I've been running this over and over in 3.8 and I haven't had any issues. 

Also, `=` doesn't appear anywhere in that formatting statement.

**Comment by 1337-server** [comment]
`Python version: 3.9.10 (main, Feb 22 2022, 13:54:07) [GCC 11.2.0]`

Reverting to the previous version of that line fixed the issue.

**Comment by shitwolfymakes** [comment]
Weird. I'll try to see if I can replicate with a Python 3.9 install in my dev environment later
