### ISSUE TITLE
Can’t install docker on unraid 

### ISSUE THREAD

**Issue by Iam2smart** [1337-server/automatic-ripping-machine#13]
The docker file doesn’t install the data in the appdata dictionary on unraid I don’t know where it installs but it causes a lot of permission errors

**Comment by 1337-server** [comment]
Could you explain a little more ?

What permission errors are you having ? 
What appdata dictionary ?

The default folder for the docker volume files are /home/arm/

**Comment by Iam2smart** [comment]
On unraid it’s different the default is /mnt/cache/appdata
It gives errors with creating the dictionary’s and a error 13 when trying to create an account saying you don’t have permission I try to go to /home/arm except it doesn’t exist

**Comment by 1337-server** [comment]
Can you post your docker run command that you used to create the container ?

**Comment by Iam2smart** [comment]
I’ll try switching it to my own paths I let you know if that works

**Comment by Iam2smart** [comment]
I’m getting these errors and I can’t change any settings won’t save
https://photos.app.goo.gl/g9QHv6XPXszU1MXw6

**Comment by 1337-server** [comment]
Those are all the correct warning. Except for the permission denied.
The file `/opt/arm/installed` only exists to stop database deletion if you accidentilly visit /setup it doesnt stop any other ARM functions.

The settings page is somewhat buggy in docker.
For the settings to update the docker needs restarted, im working on trying to fix this issue.

**Comment by Iam2smart** [comment]
Ok thanks

**Comment by 1337-server** [comment]
Ive managed to fix the bug on the settings page. I just need to push an update for the prebuilt docker image. But i cant do that right now. 

I have updated the docker branch though. 
So if you would like to rebuild the image yourself you can to solve this issue. Thanks for reporting this bug!

**Comment by Iam2smart** [comment]
Ok I can wait for the prebuilt image I’m not that handy with docker thanks for your help though!

**Comment by 1337-server** [comment]
Prebuilt image is now updated!
