### ISSUE TITLE
Docker build with vi breaks build

### ISSUE THREAD

**Issue by 1337-server** [1337-server/automatic-ripping-machine#130]
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
Trying to build the docker image with vi added, it fails. Removing vi from the build allows it to complete.

**To Reproduce**
1. Clone docker branch
2. Build

### Environment
[Debian 11]
[docker]

### Log file
N/A

**Comment by 1337-server** [comment]
This was the build that failed
https://github.com/1337-server/automatic-ripping-machine/runs/5565633478?check_suite_focus=true

This was the commit that fixed it: https://github.com/1337-server/automatic-ripping-machine/commit/be437133f7f6f9f19773bb49ca9a9b988794266c

This can be safely closed now.

**Comment by BarryHuffman** [comment]
It appears even RPM distros (*SUSE/Fedora) the "Vim" package aliases these older Vi commands.
