### ISSUE TITLE
Docker doesn't warn of wrong user ID

### ISSUE THREAD

**Issue by 1337-server** [1337-server/automatic-ripping-machine#133]
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
If the end user fails to correctly input the correct user ID for the arm user, the docker/script will silently fail with no warnings or errors given.

**To Reproduce**
1. Install docker/container via wiki instructions
2. Try to run docker with default ID (1000) arm user is normally given 1001
3. Check syslogs for failure `tail -f /var/log/syslog `

### Environment
[Ubuntu 20.04 LTS] 
[ARM v2.5.9]

### Log file
```
ARM: Starting rip
ARM: trying - docker exec -i -u 1001     -w /home/arm     arm-rippers     python3 /opt/arm/arm/ripper/main.py       -d /dev/sr0 -t ID_CDROM_MEDIA_DVD=1 -l ID_FS_LABEL=THE_HANGOVER 
systemd-udevd[7869]: sr0: Process '/opt/arm/scripts/docker_arm_wrapper.sh sr0' failed with exit code 1.
ARM: Entering docker wrapper
ARM: No ID_s

```

Possibly need to update the docker run command on DockerHub to search for arm user ID to remove this issue. Or have ARM warn the user that the ID is wrong

**Comment by shitwolfymakes** [comment]
Please see [this](https://github.com/1337-server/automatic-ripping-machine/issues/136#issuecomment-1082260049) comment
