### ISSUE TITLE
TV DVD job type is unknown/series not movie or series

### ISSUE THREAD

**Issue by macaddict89** [1337-server/automatic-ripping-machine#14]
### Description
Trying to start a dvd rip of a TV show and if nothing is set for video type it says job type is unkownnot movie or series. When I force it it says job type is seriesnot movie or series.

### Environment
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

2.4.6
[BOBS_BURGERS_S7_D1.log](https://github.com/1337-server/automatic-ripping-machine/files/5978699/BOBS_BURGERS_S7_D1.log)

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

**Comment by 1337-server** [comment]
```
DEBUG ARM: handbrake.get_track_info Sending command: HandBrakeCLI -i /dev/sr1 -t 0 --scan
ERROR ARM: handbrake.get_track_info Couldn't find a valid track.  Try running the command manually to see more specific errors.
ERROR ARM: handbrake.get_track_info Specific error is: Command 'HandBrakeCLI -i /dev/sr1 -t 0 --scan' returned non-zero exit status 127.
ERROR ARM: handbrake.get_track_info Couldn't find a valid track.  Try running the command manually to see more specific errors.
ERROR ARM: handbrake.get_track_info Specific error is: Command 'HandBrakeCLI -i /dev/sr1 -t 0 --scan' returned non-zero exit status 127.

```

Exit code 127 normally means it cant find/run the command or there is a pathing issue. 

Can you manually run the command `HandBrakeCLI -i /dev/sr1 -t 0 --scan`

**Comment by macaddict89** [comment]
sorry, you're right. In my troubleshooting this issue I installed GUI handbrake which removed handbrake-cli, but I had this issue with handbrake-cli installed.  With videotype set to series it seems to be working now, but I was unsuccessful when it was set to auto.  Don't want to upload the wrong log, so I will try to make it fail after it rips this disc.

**Comment by 1337-server** [comment]
If it is set to 'auto' you need to have an OMDB api key ([They are free](http://www.omdbapi.com/)). They api key goes into your arm.yaml config file.
With it set to 'auto' ARM calls the OMDB api to find more info about the disc such as movie/series. But even with OMDB its not perfect. OMDB does catch a large percentage though.

**Comment by macaddict89** [comment]
Gotcha. I did have a key in there but removed it to give a redacted log. I guess I found some things that it’s not catching. Thanks.

**Comment by 1337-server** [comment]
> 
> Gotcha. I did have a key in there but removed it to give a redacted log. I guess I found some things that it’s not catching. Thanks.
> […](#)
> On Feb 14, 2021, at 19:44, 1337-server ***@***.***> wrote: ﻿ If it is set to 'auto' you need to have an OMDB api key (They are free). They api key goes into your arm.yaml config file. With it set to 'auto' ARM calls the OMDB api to find more info about the disc such as movie/series. But even with OMDB its not perfect. OMDB does catch a large percentage though. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

ARM already strips keys out of the logging, so no need to worry in future.
