### ISSUE TITLE
No drivers found for installation.

### ISSUE THREAD

**Issue by TomW1605** [1337-server/automatic-ripping-machine#15]
### Description
during install getting `No drivers found for installation.` when i run `sudo ubuntu-drivers install`. the `sudo apt install ubuntu-drivers-common -y` runs fine but then it just says there are no drivers to install

### Environment
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

haven't gotten to the git clone step yet

**Comment by 1337-server** [comment]
These are from the main repo, not sure if these are required. 
I never run that step.
You would probably need to ask flamingliquid in the main repo about these, Im not sure what those are for or why ARM needs them.

**Comment by TomW1605** [comment]
ok thanks i will need to fix some other issues then because i cant get it working. i broke something a few months ago and have only just had time to try and get it up again and decided to just start from a clean build but it is not auto detecting and when i start it manually it just spits out the disk in a few seconds. i will start another issue for it.
