### ISSUE TITLE
Disc not ejected on completion

### ISSUE THREAD

**Issue by microtechno9000** [1337-server/automatic-ripping-machine#154]
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
ARM on completion of the job is failing to eject Disks and thus starting again on the same disk.
Cancelling/Abandoning the second job, ejects the disk from the drive.

```
+--------------------+--------------------------------------------------------------+
[04-17-2022 12:34:26] DEBUG ARM: models.eject Unmounted disc /dev/sr1
[04-17-2022 12:34:31] DEBUG ARM: models.eject Failed to eject /dev/sr1
[04-17-2022 12:34:31] DEBUG ARM: main.main New Title is ASTIMEGOESBY_DISC1
```

### Environment
Ubuntu 20.04.4 LTS"
* v2_devel

### Log file
[ASTIMEGOESBY_DISC1_165019888859.log](https://github.com/1337-server/automatic-ripping-machine/files/8501604/ASTIMEGOESBY_DISC1_165019888859.log)
[ASTIMEGOESBY_DISC1_165018879786.log](https://github.com/1337-server/automatic-ripping-machine/files/8501605/ASTIMEGOESBY_DISC1_165018879786.log)

**Comment by 1337-server** [comment]
Something is out of whack with your logs 

This is missing a huge chunk of output, not sure why
```
+--------------------+--------------------------------------------------------------+
|       Config       |                            Value                             |
+--------------------+--------------------------------------------------------------+
| _sa_instance_state |        <sqlalchemy.orm.state.InstanceState object at         |
|                    |                       0x7f581f515e20>                        |
+--------------------+--------------------------------------------------------------+
```

Could you post the output of `cd /opt/arm && git branch && git log -1`

**Comment by 1337-server** [comment]
Never mind, it's on the latest commit

**Comment by microtechno9000** [comment]
thanks for the fix, loaded the commit. appears to have fixed. the drive ejects disks, although did note it ejected, re-read the disk then ejected a few minutes later.

Burn that worked
```
[04-19-2022 08:28:04] DEBUG ARM: models.eject Unmounted disc /dev/sr1
[04-19-2022 08:28:09] DEBUG ARM: models.eject Failed to eject /dev/sr1
[04-19-2022 08:28:09] DEBUG ARM: main.main New Title is As-Time-Goes-By
```

Complete logs of the disks that worked, but ejected, closed then ejected again after a few minutes.
[AS_TIME_GOES_BY_SERIES_8_165036855764.log](https://github.com/1337-server/automatic-ripping-machine/files/8513447/AS_TIME_GOES_BY_SERIES_8_165036855764.log)
[AS_TIME_GOES_BY_SERIES_8.log](https://github.com/1337-server/automatic-ripping-machine/files/8513444/AS_TIME_GOES_BY_SERIES_8.log)

noting all this though, I think this bug can be closed and I can monitor for any issues

**Comment by 1337-server** [comment]
That's great, you might want to take a look at this. https://github.com/1337-server/automatic-ripping-machine/issues/82#issuecomment-897338175

Exact same issue as you're having with eject and then un-ejecting.
