### ISSUE TITLE
DVD with title '0' causes ARM fatal error

### ISSUE THREAD

**Issue by microtechno9000** [1337-server/automatic-ripping-machine#155]
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
DVD title '0' causes identify.py metadata_selector to fail
`  File "/opt/arm/arm/ui/metadata.py", line 41, in call_omdb_api
    title_info_json = urllib.request.urlopen(str_url).read()
UnboundLocalError: local variable 'str_url' referenced before assignment`

looks like str_url is defined for each of the if statement conditions, other than the final else. debug reports no paramas were provided, str_url should be defined after row 38. Not sure what it should be defined as, or just skip the omdb call?
`[04-19-2022 06:24:52] DEBUG ARM: metadata.call_omdb_api no params`

**To Reproduce**
DVD with title 0

### Environment
Ubuntu 20.04.4 LTS
v2_devel

### Log file
[0.log](https://github.com/1337-server/automatic-ripping-machine/files/8513499/0.log)
[0_165031565836.log](https://github.com/1337-server/automatic-ripping-machine/files/8513501/0_165031565836.log)

**Comment by 1337-server** [comment]
Sorry about that, Latest commit should fix this.

**Comment by 1337-server** [comment]
Didnt mean to close

**Comment by microtechno9000** [comment]
updated with commit, haven't seen issue. closing.
