### ISSUE TITLE
arm install on debian 9

### ISSUE THREAD

**Issue by thewascokid** [1337-server/automatic-ripping-machine#157]
- [ ] I have checked the wiki
- [ ] I have searched for similar issues

**Describe the bug**

**To Reproduce**
1. x
2. y
3. z

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)] 

When it runs pip3 install -r requirements.txt  I get this error

 Could not find a version that satisfies the requirement alembic==1.7.7 (from -r arm-dependencies/requirements.txt (line 1)) (from versions: 0.1.0, 0.1.1, 0.2.0, 0.2.1, 0.2.2, 0.3.0, 0.3.1, 0.3.2, 0.3.4, 0.3.5, 0.3.6, 0.4.0, 0.4.1, 0.4.2, 0.5.0, 0.6.0, 0.6.1, 0.6.2, 0.6.3, 0.6.4, 0.6.5, 0.6.6, 0.6.7, 0.7.0, 0.7.1, 0.7.2, 0.7.3, 0.7.4, 0.7.5.post1, 0.7.5.post2, 0.7.6, 0.7.7, 0.8.0, 0.8.1, 0.8.2, 0.8.3, 0.8.4, 0.8.5, 0.8.6, 0.8.7, 0.8.8, 0.8.9, 0.8.10, 0.9.0, 0.9.1, 0.9.2, 0.9.3, 0.9.4, 0.9.5, 0.9.6, 0.9.7, 0.9.8, 0.9.9, 0.9.10, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8, 1.0.9, 1.0.10, 1.0.11, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.4.0, 1.4.1, 1.4.2, 1.4.3)
No matching distribution found for alembic==1.7.7 (from -r arm-dependencies/requirements.txt (line 1))

**Comment by 1337-server** [comment]
Should now be fixed

**Comment by 1337-server** [comment]
I won't be adding support for this version, as the packages are too old. I forgot that it still comes with python 3.5
I did think about adding support, however I'm not able to commit the amount of extra work and extra maintenance it would require. Sorry about that.

-------------------
### If you wish to try it yourself anyway...

Python 3.6 isn't available to install from apt, the last version is 3.5.3. This means none of the main branch (v2_devel) will work on Debian 9 natively. It would take a lot of extra work on your part.
- Manually install at least python v3.6 and python 3.6-dev
- Clone the devel branch and [arm-dependencies](https://github.com/1337-server/arm-dependencies) branch.
- Not sure if this is needed, but possibly
    - Modify the arm-deps/[requirements.txt](https://github.com/1337-server/arm-dependencies/blob/351548473f2c9a2b522f12fe1497bfd499058f68/requirements.txt) to this version -> [requirements.txt](https://github.com/1337-server/automatic-ripping-machine/files/8548559/requirements.txt)

And even then, it may not work or run into issues.

----------------------
### Other options
- Recommended option, is to use the docker image from docker hub  - https://hub.docker.com/r/1337server/automatic-ripping-machine

- You could pull from a much older tag, Most likely less than v2.2 [tags](https://github.com/1337-server/automatic-ripping-machine/tags?after=v2.4.4)

- You could pull from the 'master' branch from the main repo [master](https://github.com/automatic-ripping-machine/automatic-ripping-machine/tree/master)

I will close this now, but if you have any more questions, let me know.
