### ISSUE TITLE
not auto starting and error from manual start

### ISSUE THREAD

**Issue by TomW1605** [1337-server/automatic-ripping-machine#16]
### Description
not autodetecting and imediatly quitting manual start. this is the terminal output:
```
tawhite@arm:~$ sudo /usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr0 | at now
warning: commands will be executed using /bin/sh
mount: /mnt/dev/sr0: WARNING: device write-protected, mounted read-only.
job 11 at Sat Feb 27 11:40:00 2021
tawhite@arm:~$
```

### Environment
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

```
tawhite@arm:/opt/arm$ git branch
* v2.5.0_dev
tawhite@arm:/opt/arm$ git log -1
commit 608c2ae7160dd0869ae78623e475ff2a0c904324 (HEAD -> v2.5.0_dev, origin/v2.5.0_dev, origin/HEAD)
Author: 1337-server <62730074+1337-server@users.noreply.github.com>
Date:   Mon Feb 15 00:24:37 2021 +0000

    Update greetings.yml
```

### Log file
[007_LTK_FEATURE_D1.log](https://github.com/1337-server/automatic-ripping-machine/files/6054304/007_LTK_FEATURE_D1.log)

**Comment by 1337-server** [comment]
It looks like your arm.yaml is missing the METADATA_PROVIDER config setting.

Adding it to your arm.yaml should solve your issue.

**Comment by TomW1605** [comment]
ok i have fixed that and added the `METADATA_PROVIDER` setting and it is working but not pulling the metadata. this is because the disk has an acronym for the title not the actual title. thats fine but when i go to do a title search i get no results. no error either just a blank search page.

**Comment by 1337-server** [comment]
Are you using omdb or tmdb as a metadata provider ? 

To use tmdb you need to set the metadata provider to "tmdb" and add your tmdb api key in the arm config to the co

If you're using omdb you just need to set the metadata provider to "omdb" and it should display results as long as you have set an omdb api key.

**Comment by TomW1605** [comment]
i am using omdb and i have added the api key. i might try and find my old one incase it is takeing a while to activate

**Comment by TomW1605** [comment]
ok that worked it must have been the new api key

**Comment by TomW1605** [comment]
but i am still not getting auto starting. there are no relavent logs that i can find so not sure what the issue is.

**Comment by 1337-server** [comment]
Can you run ARM manually and post the output ?

**Comment by TomW1605** [comment]
the log or terminal output? either way i have 2 running and will post when one is done

**Comment by TomW1605** [comment]
[007_LTK_FEATURE_D1_161448636521.log](https://github.com/1337-server/automatic-ripping-machine/files/6056386/007_LTK_FEATURE_D1_161448636521.log)
here is the debug log of the manual rip

**Comment by 1337-server** [comment]
I cant see anything wrong. Maybe removing the udev rule and re adding it ?

**Comment by TomW1605** [comment]
i will try that when one of the current jobs finishes. does that need a reboot?

**Comment by 1337-server** [comment]
Yes

**Comment by TomW1605** [comment]
ok in that case i will do it in the morning when all the current jobs are done and i will reboot between deleting and adding as well

**Comment by TomW1605** [comment]
also sorry for the flood of issues and PRs

**Comment by 1337-server** [comment]
No worries, PR and issues are always welcome!

**Comment by TomW1605** [comment]
ok so i removed and replaced the udev rule but it did not work. i did have a look at the syslog when inserting the disk and the first log from the wrapper script is there but it looks like it does not actually call the python. here is the log
```
Mar  2 12:29:39 arm ARM: [ARM] Starting ARM on sr0
Mar  2 12:29:39 arm systemd[1]: Created slice User Slice of UID 1001.
Mar  2 12:29:39 arm systemd[1]: Starting User Runtime Directory /run/user/1001...
Mar  2 12:29:39 arm systemd[1]: Finished User Runtime Directory /run/user/1001.
Mar  2 12:29:39 arm systemd[1]: Starting User Manager for UID 1001...
Mar  2 12:29:39 arm systemd[3603]: Reached target Paths.
Mar  2 12:29:39 arm systemd[3603]: Reached target Timers.
Mar  2 12:29:39 arm systemd[3603]: Starting D-Bus User Message Bus Socket.
Mar  2 12:29:39 arm systemd[3603]: Listening on GnuPG network certificate management daemon.
Mar  2 12:29:39 arm systemd[3603]: Listening on GnuPG cryptographic agent and passphrase cache (access for web browsers).
Mar  2 12:29:39 arm systemd[3603]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
Mar  2 12:29:39 arm systemd[3603]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Mar  2 12:29:39 arm systemd[3603]: Listening on GnuPG cryptographic agent and passphrase cache.
Mar  2 12:29:39 arm systemd[3603]: Listening on debconf communication socket.
Mar  2 12:29:39 arm systemd[3603]: Listening on REST API socket for snapd user session agent.
Mar  2 12:29:39 arm systemd[3603]: Listening on D-Bus User Message Bus Socket.
Mar  2 12:29:39 arm systemd[3603]: Reached target Sockets.
Mar  2 12:29:39 arm systemd[3603]: Reached target Basic System.
Mar  2 12:29:39 arm systemd[3603]: Reached target Main User Target.
Mar  2 12:29:39 arm systemd[3603]: Startup finished in 54ms.
Mar  2 12:29:39 arm systemd[1]: Started User Manager for UID 1001.
Mar  2 12:29:39 arm systemd[1]: Started Session c21 of user arm.
Mar  2 12:29:39 arm systemd[1]: session-c21.scope: Succeeded.
Mar  2 12:29:39 arm ARM: [ARM] ARM Webgui running.
Mar  2 12:29:40 arm postfix/sendmail[3621]: fatal: open /etc/postfix/main.cf: No such file or directory
Mar  2 12:29:42 arm python3[1216]: 192.168.3.1 - - [02/Mar/2021 12:29:42] "#033[37mGET /joblist HTTP/1.0#033[0m" 200 -
Mar  2 12:29:47 arm python3[1216]: 192.168.3.1 - - [02/Mar/2021 12:29:47] "#033[37mGET /joblist HTTP/1.0#033[0m" 200 -
Mar  2 12:29:50 arm systemd[1]: Stopping User Manager for UID 1001...
Mar  2 12:29:50 arm systemd[3603]: Stopped target Main User Target.
Mar  2 12:29:50 arm systemd[3603]: Stopped target Basic System.
Mar  2 12:29:50 arm systemd[3603]: Stopped target Paths.
Mar  2 12:29:50 arm systemd[3603]: Stopped target Sockets.
Mar  2 12:29:50 arm systemd[3603]: Stopped target Timers.
Mar  2 12:29:50 arm systemd[3603]: dbus.socket: Succeeded.
Mar  2 12:29:50 arm systemd[3603]: Closed D-Bus User Message Bus Socket.
Mar  2 12:29:50 arm systemd[3603]: dirmngr.socket: Succeeded.
Mar  2 12:29:50 arm systemd[3603]: Closed GnuPG network certificate management daemon.
Mar  2 12:29:50 arm systemd[3603]: gpg-agent-browser.socket: Succeeded.
Mar  2 12:29:50 arm systemd[3603]: Closed GnuPG cryptographic agent and passphrase cache (access for web browsers).
Mar  2 12:29:50 arm systemd[3603]: gpg-agent-extra.socket: Succeeded.
Mar  2 12:29:50 arm systemd[3603]: Closed GnuPG cryptographic agent and passphrase cache (restricted).
Mar  2 12:29:50 arm systemd[3603]: gpg-agent-ssh.socket: Succeeded.
Mar  2 12:29:50 arm systemd[3603]: Closed GnuPG cryptographic agent (ssh-agent emulation).
Mar  2 12:29:50 arm systemd[3603]: gpg-agent.socket: Succeeded.
Mar  2 12:29:50 arm systemd[3603]: Closed GnuPG cryptographic agent and passphrase cache.
Mar  2 12:29:50 arm systemd[3603]: pk-debconf-helper.socket: Succeeded.
Mar  2 12:29:50 arm systemd[3603]: Closed debconf communication socket.
Mar  2 12:29:50 arm systemd[3603]: snapd.session-agent.socket: Succeeded.
Mar  2 12:29:50 arm systemd[3603]: Closed REST API socket for snapd user session agent.
Mar  2 12:29:50 arm systemd[3603]: Reached target Shutdown.
Mar  2 12:29:50 arm systemd[3603]: systemd-exit.service: Succeeded.
Mar  2 12:29:50 arm systemd[3603]: Finished Exit the Session.
Mar  2 12:29:50 arm systemd[3603]: Reached target Exit the Session.
Mar  2 12:29:50 arm systemd[1]: user@1001.service: Succeeded.
Mar  2 12:29:50 arm systemd[1]: Stopped User Manager for UID 1001.
Mar  2 12:29:50 arm systemd[1]: Stopping User Runtime Directory /run/user/1001...
Mar  2 12:29:50 arm systemd[1460]: run-user-1001.mount: Succeeded.
Mar  2 12:29:50 arm systemd[1]: run-user-1001.mount: Succeeded.
Mar  2 12:29:50 arm systemd[1]: user-runtime-dir@1001.service: Succeeded.
Mar  2 12:29:50 arm systemd[1]: Stopped User Runtime Directory /run/user/1001.
Mar  2 12:29:50 arm systemd[1]: Removed slice User Slice of UID 1001.
```

**Comment by TomW1605** [comment]
i think this is the issue `Mar  2 12:29:40 arm postfix/sendmail[3621]: fatal: open /etc/postfix/main.cf: No such file or directory`

**Comment by TomW1605** [comment]
i tried running this line from the wrapper script `/bin/su -l -c "echo /usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr0 | at now" -s /bin/bash arm` and that error came up. but when i run python directly like the trouble shooting says it works

**Comment by 1337-server** [comment]
It's trying to send a notification of the error but it's failing. Probably because you don't have postfix send Mail installed. 

Could you setup one of the apprise notifications ? It makes things a lot easier to debug as it will send most errors via your chosen service.

**Comment by TomW1605** [comment]
i couldn't get apprise to work so i just setup sendmail properly and got the error emailed. it was a permissions error for the database. i think the way i created the arm user accidentally had the whole user folder owned by root. now it is working and the apprise notifications are working just not for the errors.
