### ISSUE TITLE
Ripping series only outputting one file 

### ISSUE THREAD

**Issue by GamerBene19** [1337-server/automatic-ripping-machine#163]
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
When ripping a series only one file is put into the output directory

**Expected result**
I would expect all episodes of a series to be present with name something like `Sample Series (1972) - Episode 1.mkv`

**To Reproduce**
1. Set method to `mkv` (I have it set to that, but don't think its relevant here)
2. Rip disc containing multiple episodes of a series
3. Observe all episodes beeing put into `raw` but only one (I think the first) beeing put into `completed`

### Environment
Ubuntu 20.04.4, on commit `8d32bab757f090d474d85c579037021771d19fec` of branch `v2_devel`

### Log file (cut to relevant section at the end)
[Sample Series_DISC1.log](https://github.com/1337-server/automatic-ripping-machine/files/8596455/Sample.Series_DISC1.log)

**Comment by 1337-server** [comment]
Reopened as it needs testing fully, but this should fix the issue.

**Comment by GamerBene19** [comment]
> as it needs testing fully

How would I do that? Do just I update my existing install? If so: How?

**Comment by 1337-server** [comment]
Yes its just a small update to your install. 
This tells you how to update.
https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/upgrading

**Comment by GamerBene19** [comment]
I've tried out the changes. They don't seem to work. I don't get any files output anymore (could also be because of the other changes made since install though).

Here's the relevant log section again
[Sample Series.log](https://github.com/1337-server/automatic-ripping-machine/files/8597458/Sample.Series.log)

As far as I can tell it tries to move the files from my `transcode` directory. But there are no files there as I skip transcoding.

**Comment by 1337-server** [comment]
Ok, I think I got it. I'm going to test a bit more before I push, but I've narrowed it down to this line.

https://github.com/1337-server/automatic-ripping-machine/blob/49505309800e454e5d7266e26e3735afbf0d8a25/arm/ripper/arm_ripper.py#L73

It pushes the out_path into move files, but if transcoding is skipped, in_path should be used. As out_path (TRANSCODE_PATH) will be empty.

I'll update when I have fully tested a fix.

**Comment by GamerBene19** [comment]
My initial issue is solved (all episodes of a series are copied to the output directory). However when a movie now has more than one file. The largest one is beeing left in the `extras` dir as `title_t<number>` instead of being copied (and renamded to `<movie title> (<year>).mkv` in the folder above `extras`.

**Comment by 1337-server** [comment]
This should finally fix it, let me know if not.

**Comment by GamerBene19** [comment]
Thanks for the quick fix. Sadly I won't be able to test this till at least friday. I'll give you an update then!

**Comment by 1337-server** [comment]
No worries, there is no rush.

**Comment by GamerBene19** [comment]
I just tested a movie. It seems to work. I will test series shortly but I expect them to work too

However I've noticed something different. Before I could change the title during ripping and the output would get placed into the folder with the new title (the old folder that was created at the beginning still existed, but you could just delete it afterwards). Now, if I don't update the title before the ripping begins the file will not be placed into a folder with the new name.

**Comment by 1337-server** [comment]
It should now update if you set a custom title, or update title from search

**Comment by GamerBene19** [comment]
So after a bit of testing this weekend I think this issue can be closed. Series are ripped as expected and other behaviour is the same (again)
