### ISSUE TITLE
Consider changing "find us on github link"

### ISSUE THREAD

**Issue by charmarkk** [1337-server/automatic-ripping-machine#164]
Presently, the link on the UI goes to the original repo. I wonder if it would make sense to link to yours (1337-server), as you've done a lot of work and are many commits ahead of/to the side of the main one. 😊 I can write a quick PR for you changing some of that if you'd like the extra credit. Gotta give it where it's due!

**Comment by charmarkk** [comment]
Maybe I should've checked the number of commits - you've pushed a lot of them up to the main repo. 😉

**Comment by 1337-server** [comment]
Yeah, I just got write access to the main repo, so this probably isn't necessary now, as the main repo will always be updated.

Great idea though. I'll close this now.


Thanks
