### ISSUE TITLE
Abandoning Job not working

### ISSUE THREAD

**Issue by GamerBene19** [1337-server/automatic-ripping-machine#166]
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
On the current release the "Abandon Job" button does nothing.

**To Reproduce**
1. Insert disc
2. Try to abandon job

**Comment by 1337-server** [comment]
I can't reproduce this

`http://192.,1,1,1,:xxxx/json?job=61&mode=abandon`
```
{
    job: "61"
    mode: abandon"
    success: true
}
```

What stage was the job at ?  
Did you check the webui.log ?

**Comment by GamerBene19** [comment]
Nevermind. I had JS disabled. Classical PEBKAC error.
