### ISSUE TITLE
Importing custom Handbrake Preset

### ISSUE THREAD

**Issue by hrast01** [1337-server/automatic-ripping-machine#176]
**Is your feature request related to a problem? Please describe.**
Handbrake doesn't handle surround sound tracks the way I would prefer in Super HQ 1080p30 Surround.  I want to pass through essentially all the audio for the selected language.

**Describe the solution you'd like**
I'd like to be able to import a custom preset(s) from Handbrake created elsewhere and have it added to the container.

**Describe alternatives you've considered**
I've considered doing the conversion on a standalone system, but then it sort of loses the point of ARM.

**Are you able to help code/implement this feature ?**
Yes

**Comment by 1337-server** [comment]
automatic-ripping-machine/#447

Should show  you how to do this. It just means passing in the preset file to arm.

**Comment by hrast01** [comment]
I literally just figured this out in the past 20 minutes.  Thanks for the direction!
