### ISSUE TITLE
Unable to write to SMB

### ISSUE THREAD

**Issue by goldrush8** [1337-server/automatic-ripping-machine#178]
- [x] I have checked the wiki
- [x] I have searched for similar issues

I will start by saying that i am not at all skilled with Ubuntu and only mildly with SMBs and Docker but i feel comfortable enough to try and get ARM going.

I have been attempting to get ARM to write transcode, raws and complete to my SMB and have been unsuccessful. Every attempt results in an exit of ARM.

I have read the logs and this is not a permission issue, i have gone forward and backward granting every last permission i can and still receive this issue.
Fstab is as follows
`//serverIP/serverstoragename /mnt/media cifs guest,exec,auto,users,domain=WORKGROUP,uid=1001,gid=1001,suid,exec,dir_mode=0777,file_mode=0777 0 0`
I have also played with adding just about every option i can think to the fstab, adjusting user and group IDs, ensuring the SMB was set up correctly, im am simply out of ideas at this point and feel i am either missing something or something is broken in ARM.
I have attempted to run with noperm arg in an attempt to bypass restrictions and that did not fix the issue either.

From the server itself i am able to browse, create and execute as the main user

**To Reproduce**
Install dev build of Docker as instructed.
Changed Raw transcode and complete to
/mnt/media/ARM/raw
/mnt/media/ARM/transcode
/mnt/media/ARM/complete

Those folders exist within the SMB but upon inserting a disk results in 
'utils.make_dir Couldn't create a directory at path: /mnt/media/ARM/transcode/unidentified'

### Environment
Distributor ID: Ubuntu
Description:    Ubuntu 22.04 LTS
Release:        22.04
Codename:       jammy
1337server/automatic-ripping-machine:dev_build

### Log file

[MissKobayashi_D2_165284266974.log](https://github.com/1337-server/automatic-ripping-machine/files/8713334/MissKobayashi_D2_165284266974.log)

**Comment by goldrush8** [comment]
Follow up, i have reinstalled everything including ubuntu and the issue persists. 
This line stuck out to me on the log as a potential candidate for the root cause, but im not completely sure

`[05-19-2022 04:06:24] ERROR ARM: utils.try_add_default_user [Errno 13] Permission denied: '/opt/arm/installed'`

This may after all be an issue for me to figure out. I have given permissions every which way but ubuntu doesnt want to seem to allow non-root to access the SMB for some reason even with an open ATL. I will return with either a solution or to close

**Comment by goldrush8** [comment]
Alright, i believe i have gotten this now, once i resolved my SMB issues it seems i had to add new volumes to the docker container itself, in my case /mnt/media:/mnt/media
and that seemed to resolve the odd errno 13 issue i was receiving

**Comment by gingerbeardman** [comment]
@goldrush8 this is in the installation instructions https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/docker

**Comment by goldrush8** [comment]
@gingerbeardman The installation instructions not only do not cover necessity for SMB or any information for SMB nor does it mention anywhere the need to add additional volumes to docker for ARM to access the SMB.
The link you have provided only gives the base locations that ARM docker needs and does not mention anywhere the need to map additional volumes. That page simply states the need to mount disk drives which was done in fstab prior to posting this issue.
As i stated this issue directly pertained to ARM accessing SMB and not the mounting of the disk drives themselves.
As the dev has stated in other bug reports the main :latest build is unmanaged and recommends using the dev build as i have done, which no longer needs the files placed and will attempt to mount the drives itself without fstab entries.
The solution to my problem in short was adding the SMB share to the ARM docker volumes and was completely missed in the documentation you provided

**Comment by gingerbeardman** [comment]
I see, thanks for the clarification.
