### ISSUE TITLE
📚 Installation WIKI link not working

### ISSUE THREAD

**Issue by poppab** [1337-server/automatic-ripping-machine#207]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug?

 This is the link for the install wiki but it just points back to the main ARM page "https://github.com/1337-server/automatic-ripping-machine/wiki/". How do i get to the installation wiki?

Thanks

### The page

https://github.com/1337-server/automatic-ripping-machine/wiki/

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337-server** [comment]
Where did you find this link ?
I thought I removed them all.

The new place for all documentation is https://github.com/automatic-ripping-machine/automatic-ripping-machine/wiki/

**Comment by 1337-server** [comment]
Should now be resolved

**Comment by 1337-server** [comment]
Sorry about that, I thought you meant on the ARM wiki and not the repos' README.

Thanks!
