### ISSUE TITLE
[FEATURE] UI to change username/password

### ISSUE THREAD

**Issue by TomW1605** [1337-server/automatic-ripping-machine#22]
### Description
how do you change the username and password?

### Environment
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

```
tawhite@arm:/opt/arm$ git branch
* v2.5.0_dev
tawhite@arm:/opt/arm$ git log -1
commit 608c2ae7160dd0869ae78623e475ff2a0c904324 (HEAD -> v2.5.0_dev, origin/v2.5.0_dev, origin/HEAD)
Author: 1337-server <62730074+1337-server@users.noreply.github.com>
Date:   Mon Feb 15 00:24:37 2021 +0000

    Update greetings.yml
```

**Comment by 1337-server** [comment]
There isnt a way to change it without editing the database. I normally use DB Browser for SQLite but this isnt the best/easiest way. It really would be better to have a reset option.

**Comment by TomW1605** [comment]
ok i will edit the db when i shutdown to try and fix the auto start. i will leave this job open and make it a request for adding this to the UI that i might have a look at since i have been working on UI all day.

**Comment by TomW1605** [comment]
> There isnt a way to change it without editing the database. I normally use DB Browser for SQLite but this isnt the best/easiest way. It really would be better to have a reset option.

how do you set the password? is there a hash function i can use in the python to generate a hash?

**Comment by 1337-server** [comment]
> 
> 
> > There isnt a way to change it without editing the database. I normally use DB Browser for SQLite but this isnt the best/easiest way. It really would be better to have a reset option.
> 
> how do you set the password? is there a hash function i can use in the python to generate a hash?

Yes you need the hash from the db then you can run 
```
import bcrypt
x = bcrypt.hashpw("your-new-password".encode('utf-8'), "hash-from-database".encode('utf-8'))
print(x.decode())

```

**Comment by 1337-server** [comment]
Latest commit now lets you bypass the 1 admin account limit, or update the password for an account.

**Comment by TomW1605** [comment]
i had a look at this and while it does work i think it is not quite what is needed. because we dont have an email address there is no way to verify that the user changing the password because they forgot their old one is the actual user. i think a change password page is still needed but that will require the user to enter their old password to change it. i think if a user forgets their password a DB reset or edit should be required. i think access to the server file system is enough verification that they are the server owner.

**Comment by 1337-server** [comment]
My original idea was to have the forgot password link use a master password from the arm.yaml that would allow to either drop the user table or update the details. but i didn't have time to code it fully. So used something very simple for now.

**Comment by 1337-server** [comment]
Closing as this is now added!
