### ISSUE TITLE
Python 3.9.2 on Debian 11 w/ Git Diff Patch that fixes "Rip DVD as Data" and "= alignment" failures

### ISSUE THREAD

**Issue by mneimeyer** [1337-server/automatic-ripping-machine#223]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### I have checked the wiki

- [X] I have searched the wiki for this problem

### Does this issue exist in the latest version?

- [X] I'm using the latest release

### Describe the bug?

Two Issues:
1. Error when ripping that states "= alignment not allowed in string format specifier"
2. None Tracks found by Handbrake (sort of) resulting in rip as Data Discs.

Additional issue in that for 1 it said that a trace would follow (in the logs) and didn't.

Additional complexity in that arm_wrapper.sh did properly identify the disc as DVD so /var/logs/arm.log wasn't useful.

### To Reproduce

Installed ARM on fresh install of Debian 11. Tried to rip DVDs.

### What OS are you seeing the problem on?

Debian 11

### ARM Release Version or Git hash (You can find this in the arm settings page)

d33a6c6b3418e01f764a34f5fdcb097d7c50de6d

### Expected behavior?

Proper Rip as DVD and without faulting

### Relevant log output

```shell
I deleted the logs while debugging... Sorry...
```

### Anything else?

Git Diff attached. I MIGHT be able to make a pull request but these are two tiny changes in handbrake.py and my dev environment is borked right now and my repository fork is woefully behind.

The first is the filename line and is the result of trying to format a string as a number. 
Fix: Changed ":02" to ":0>2"

Comment: As detailed in this Stackoverflow post. Not sure if there's a safer/better way to handle this but this worked for me.
https://stackoverflow.com/questions/36044676/text-formatting-error-alignment-not-allowed-in-string-format-specifier. 

The second is the Regex for result includes an unescaped parenthesis set.
Fix: Removed the "(s)" from the Regex.

[ARM Issues 2022-08-26.txt](https://github.com/1337-server/automatic-ripping-machine/files/9434933/ARM.Issues.2022-08-26.txt)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by 1337-server** [comment]
Sorry about the late reply.

Please use the main repo https://github.com/automatic-ripping-machine/automatic-ripping-machine
