### ISSUE TITLE
[FEATURE] set domain name for use in apprise notifications

### ISSUE THREAD

**Issue by TomW1605** [1337-server/automatic-ripping-machine#23]
### Description
a way to set the domain name for use in apprise notifications so links work right

**Comment by 1337-server** [comment]
Do you mean the link that is sent via notifications to edit the job ? If so ARM tries to automatically find your ip if `WEBSERVER_IP` is set to `x.x.x.x`
You can set this to your own needs. 

If this isn't what you meant can you explain a little more ?

**Comment by TomW1605** [comment]
that is what i am talking about but i dont want an ip. is that possible or will that break the webserver

**Comment by 1337-server** [comment]
There shouldnt be anything that causes issues if you set it to a domain name.

**Comment by TomW1605** [comment]
i was assuming that flask uses that config parameter as the bind ip so setting it to a domain name would break it

**Comment by 1337-server** [comment]
Yes that is correct. You could simply modify main.py 
```
        utils.notify(job, "ARM notification",
                     f"Found disc: {job.title}. Disc type is {job.disctype}. Main Feature is {job.config.MAINFEATURE}"
                     f".  Edit entry here: http://" + str(check_ip()) + ":"
                     f"{job.config.WEBSERVER_PORT}/jobdetail?job_id={job.job_id}")
```
To your own liking (replacing the `" + str(check_ip()) + "` with your domain name), and this wont effect anthing else.

**Comment by TomW1605** [comment]
since i am messing around with the configs anyway i might just add a config variable. and if it is blank it just uses the ip
