### ISSUE TITLE
no jobs shown when not loged in

### ISSUE THREAD

**Issue by TomW1605** [1337-server/automatic-ripping-machine#35]
because the json route requiers login there are no jobs shown when you are not loged in.

https://github.com/1337-server/automatic-ripping-machine/blob/3933405c9203338bf9f7d32e64b519c6e40fdadb/arm/ui/routes.py#L302

**Comment by 1337-server** [comment]
This is working as intended. However I'm not sure this is for the best. It really depends on the end user. Personally i would prefer to show nothing unless logged in.

**Comment by TomW1605** [comment]
i don't disagree with this but the problem is that there is nothing to indicate that you need to log in and there is no login button. the only way to do it is to go to the logs or the database and force a login. if you do want to show nothing when not logged in then you should have the home page require login.

i also think this should be optional. for example i have it already locked behind nginx auth so i don't want to have to login again just to view the running jobs.

**Comment by 1337-server** [comment]
This is a very good point.

I will look into allowing/switching of security modes.

**Comment by 1337-server** [comment]
Ok, it appears its very simple to allow the end user to enable or disable requiring login 

All that is needed is to add `app.config['LOGIN_DISABLED'] = True` to `/opt/arm/arm/ui/__init__.py`

Something like this
```
# We should really gen a key for each system
app.config['SECRET_KEY'] = "Big secret key"
app.config['LOGIN_DISABLED'] = True
db = SQLAlchemy(app)
```

It will need more work to add it to the arm.yaml, but i will work on this.

**Comment by TomW1605** [comment]
would this disable it for the whole site or just the home page?

if it is the whole site that is fine but it might be worth then having the homepage also require login. or add some other message saying that you need to login to view jobs. at the moment the only way to know that you need to login to view jobs is to look at the browser logs and see the auth errors trying to access the json endpoint.

**Comment by 1337-server** [comment]
That would disable it for the whole site.

I will add the lock the index, and add a config for turning login on/off from the arm.yaml.

**Comment by 1337-server** [comment]
Latest commit should now resolve this issue.
