### ISSUE TITLE
http://WEBSERVER_IP:WEBSERVER_PORT/setup not found

### ISSUE THREAD

**Issue by TomW1605** [1337-server/automatic-ripping-machine#4]
### Description
when i go to `http://WEBSERVER_IP:WEBSERVER_PORT/setup` i get a 404. i am substituting the correct values and when i remove setup i get to the main page just fine.

### Environment
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"

git branch/commit: v2.3_dev/8a69904db336c484d36cd8609402744410529725

### Log file
none generated

**Comment by 1337-server** [comment]
Are you able to login ?
Does it redirect or does the page stay static on 404 ?

Thanks

**Comment by TomW1605** [comment]
i have looked into it more and it is redirecting to the error page

**Comment by TomW1605** [comment]
i got around it by inserting a disk and letting it create the database then manually going to setup_stage2

**Comment by 1337-server** [comment]
Yeah sorry about this, this is a known bug that is fixed in v2.4

**Comment by TomW1605** [comment]
ok thanks.
