### ISSUE TITLE
[REQUEST] looser search

### ISSUE THREAD

**Issue by TomW1605** [1337-server/automatic-ripping-machine#40]
i was ripping an old movie today and found that when i searched for `THE GANGS ALL HERE` i got nothing but when i changed it to `THE GANG'S ALL HERE` i got the movie i was looking for. im not sure how the search works or if this is possible but it would be great if it could be looser on its matches.

**Comment by 1337-server** [comment]
I have experienced this but i cant find any work around to make the search looser with omdb.

This is why i made the change to tmdb as it was much looser with search results finding more (only slightly) than omdb

**Comment by TomW1605** [comment]
ok thanks for letting me know
