### ISSUE TITLE
current dev branch

### ISSUE THREAD

**Issue by TomW1605** [1337-server/automatic-ripping-machine#43]
what is your current dev branch? i have been working off v2.5.0_dev but just noticed that v2_devel is the default now. should i update my fork to use v2_devel or keep working off v2.5.0_dev?

**Comment by 1337-server** [comment]
v2_devel is dev branch and its the branch i use. 
I don't think there are any changes that you don't have though, the only difference for now is the name.

**Comment by TomW1605** [comment]
ok thanks. all my directory changes are on v2.5.0_dev but i dont think that is an issue for now (but might become one if i miss a change that breaks it)

**Comment by 1337-server** [comment]
Yeah apologies, the v2.x naming convention was a terrible idea of mine.

I eventually want to remove all others and only keep `v2_master` for stable and `v2_devel` for testing/development. That should make things a lot clearer for everyone in future.

**Comment by TomW1605** [comment]
ok i will update to v2_devel and work off that
