### ISSUE TITLE
ui shows transcoding while it is ripping

### ISSUE THREAD

**Issue by TomW1605** [1337-server/automatic-ripping-machine#5]
### Description
ui shows transcoding while it is ripping. not much more to say

**Comment by 1337-server** [comment]
Can you attach your log file from the job ?

**Comment by TomW1605** [comment]
here is the log
[Goldeneye.log](https://github.com/1337-server/automatic-ripping-machine/files/5758804/Goldeneye.log)

**Comment by 1337-server** [comment]
Can you change your log level to `DEBUG` in your arm.yaml

From what i can tell from the log it is transcoding, so the UI is showing correct information, but without seeing the DEBUG log i cant really pinpoint the issue.

**Comment by TomW1605** [comment]
ok but it has not started writing the output file yet so i dont think it is transcoding.

also it will need to wait for the next disk. i have changed it to debug but it has not switched so i assume i need to restart to take effect.

**Comment by 1337-server** [comment]
No you dont need to restart for the debugging to change levels. It will update with the next disc.

**Comment by 1337-server** [comment]
As far is i can tell this is working as intented.

**Comment by TomW1605** [comment]
yes this is working as intended. i had it set to transcode directly from the disk.
