### ISSUE TITLE
Things not identifying devel

### ISSUE THREAD

**Issue by cpesko** [1337-server/automatic-ripping-machine#51]
[21:51:01] mux: track 0, 142235 frames, 953401129 bytes, 1285.94 kbps, fifo 2048
[21:51:01] mux: track 1, 278024 frames, 118337612 bytes, 159.61 kbps, fifo 4096
[21:51:01] mux: track 2, 185349 frames, 284696064 bytes, 384.00 kbps, fifo 4096
[21:51:01] Finished work at: Thu Apr  1 21:51:01 2021

[21:51:01] libhb: work result = 0

Encode done!
HandBrake has exited.

[01-04-2021 21:51:01] INFO ARM: Track #2 of 2. Length (261) is less than minimum length (600).  Skipping
[01-04-2021 21:51:01] INFO ARM: Handbrake processing complete
[01-04-2021 21:51:03] INFO ARM: job type is unknown not movie or series, not moving.
[01-04-2021 21:51:03] INFO ARM: EMBY_REFRESH config parameter is false.  Skipping emby scan.
[01-04-2021 21:51:03] INFO ARM: Removing raw path - None
[01-04-2021 21:51:03] INFO ARM: Removing raw path - /home/arm/media/transcode/unidentified/DANGEROUS_MINDS ()
[01-04-2021 21:51:03] INFO ARM: Removing raw path - /dev/sr0
[01-04-2021 21:51:05] INFO ARM: ARM processing complete

**Comment by cpesko** [comment]
Do we not use omdb anymore? Search function broken.

**Comment by 1337-server** [comment]
Did you make sure to select omdb as your metadata provider ?

Is it the search function in the ui or the auto ident when you insert a disc ?

**Comment by cpesko** [comment]
What is the auto indent? Ya I am using default arm.sample.yaml cp to arm.yaml with my omdb key.. Where is the auto indent?

**Comment by cpesko** [comment]
btw in the docker one I noticed you have a random omdb key in there you may want to take it out.... in the arm.sample.

**Comment by 1337-server** [comment]
The auto ident (automatic identification) happens when ever you insert a disc. It happens in /opt/arm/arm/ripper/identify.py

But the search function in the ui is totally different process. Its when you click 'title search'

Which one isnt working.


Thanks for letting me know, ill remove it.

**Comment by cpesko** [comment]
When I insert disc it grabs the title off dvd. So it could be none but doesnt grab the scrapper image. UI search function doesnt work even if I insert year.

**Comment by 1337-server** [comment]
Can you attach the full logfile ?

Download it and drag it into the comment box

**Comment by cpesko** [comment]
well there must be something diff. I grabbed identify.py from patch 2 and its working insert way. search ui still broke.

**Comment by cpesko** [comment]
[DIAMONDS_161732887359.log](https://github.com/1337-server/automatic-ripping-machine/files/6247475/DIAMONDS_161732887359.log)

**Comment by cpesko** [comment]
[DANGEROUS_MINDS_161733233194.log](https://github.com/1337-server/automatic-ripping-machine/files/6247486/DANGEROUS_MINDS_161733233194.log)

This one is working with patch-2 identify.py The Diamonds log is suppose to be 007 Diamonds are forever

**Comment by cpesko** [comment]
[DIAMONDS_161732015292.log](https://github.com/1337-server/automatic-ripping-machine/files/6247515/DIAMONDS_161732015292.log)
sorry heres a full one

**Comment by 1337-server** [comment]
Can you enable the debug logging and try the rip again ?  The info log wont show any details.

You can enable Debugging by changing `LOGLEVEL` in your [arm.yaml](https://github.com/1337-server/automatic-ripping-machine/wiki/arm.yaml) to `LOGLEVEL: "DEBUG"`

**Comment by cpesko** [comment]
[DANGEROUS_MINDS_161734130931.log](https://github.com/1337-server/automatic-ripping-machine/files/6248158/DANGEROUS_MINDS_161734130931.log)
so this one is showing the correct title with scrapper in arm. but not moving right I guess. I am using the identify.py from patch-2 cause the ident is apparently working there. Search function still doesnt work right I assume that is in the route.py somewhere...

**Comment by 1337-server** [comment]
If you're using a different identify.py from another branch, debugging this issue becomes impossible.

You would need to re-add the original identify.py try a rip in debug mode, then attach your log.

**Comment by 1337-server** [comment]
I managed to reproduce this issue, its only an issue with omdb. TMDB is was unaffected. Pushed a potential fix for it. Hopefully this solves the issue.

Let me know is this still happens.
