### ISSUE TITLE
questions about setup

### ISSUE THREAD

**Issue by emmakat** [1337-server/automatic-ripping-machine#52]
### Description
I'm trying this Docker build out and I have a couple of n00b question. 
1) regarding "The UID and GID must exists outside the container", I don't understand how to check that this is configured properly.

2) I'd like to map to an internal storage drive, separate from the SSD. I think I don't understand how to give the arm user permissions to the drive locations (or perhaps they need binding vs volume?), and I don't understand if I am to make the folder paths myself prior to running this, or if it's supposed to create them itself automatically. For now, I will run it with the default set up to verify if that works, but I'm curious about how I can fix this issue.
I modified my docker run to look like this:
docker run -d \
   -p "8080:8080" \
   -e UID="1000" -e GID="1000" \
   -v "/home/arm:/home/arm" \
   -v "/media/jd/Storage/Music:/home/arm/Music" \
   -v "/media/jd/Storage/config:/home/arm/config" \
   -v "/media/jd/Storage/logs:/home/arm/logs" \
   -v "/media/jd/Storage/media:/home/arm/media" \
   --device="/dev/sr0:/dev/sr0" \
   --device="/dev/sr1:/dev/sr1" \
   --device="/dev/sr2:/dev/sr2" \
   --device="/dev/sr3:/dev/sr3" \
   --device="/dev/sr4:/dev/sr4" \
   --device="/dev/sr5:/dev/sr5" \
   --device="/dev/sr6:/dev/sr6" \
   --privileged \
   --restart "always" \
   --name "arm-rippers" \
   1337server/automatic-ripping-machine:latest

### Environment
[DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"]

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

**Comment by 1337-server** [comment]
You need a user 'arm' on the host machine to match the guid and uid that you push into the container. You can find this out by running
`id arm` on the host machine, the numbers it gives you there need to be used for passing into the container image

So if id arm gives back
`uid=1000(arm) gid=1000(arm) groups=1000(arm),24(cdrom),44(video),107(render)`

You can use 
`-e UID="1000" -e GID="1000" ` in your docker run command, but if the values are different they need to match the host machine.

The docker image should create all the folders needed to get started. One of the common problems i have when spinning up the docker image is file permission settings. For me i needed to make sure the host 'arm' user had write permissions to each of the volumes.

> or perhaps they need binding vs volume?

This may be a very good point, i am very new to docker images. And for the more complicated topics i wont be of much use. Sorry i cant be of more help.

**Comment by emmakat** [comment]
ah, this is super helpful! I see now that I'm trying all this from my own user account, and I needed to have have created an arm user first, and start over from there. I'll compile all my learnings/fixes and see if I can make a PR for some readme improvements that might help someone else! - thanks again for working on this cool project and helping me with my questions :)
