### ISSUE TITLE
search interface changes

### ISSUE THREAD

**Issue by TomW1605** [1337-server/automatic-ripping-machine#54]
just a few small changes that would make the search interface better.

1. keep the search and year bar at the top of the results so you can quickly redo a search.
2. return to home after updating a title. there is nothing more to do on the update title screen so why stay there.
3. if there are no results for a title + year search try searching for the title alone or error back to the main search screen

**Comment by 1337-server** [comment]
Now fully added!
Great suggestions, will close this now.
