### ISSUE TITLE
Apprise cant handle missing config types

### ISSUE THREAD

**Issue by TomW1605** [1337-server/automatic-ripping-machine#58]
if there is a notification type missing from the app rise config it crashes. this is annoying when a new one is added. this just needs an exception handler for key errors.

**Comment by 1337-server** [comment]
The whole setting page needs re-written to be static anyway. I hope to be able to get this done soon.

**Comment by 1337-server** [comment]
Can you explain a little more ? 
All of the configs should be in the default apprise.yaml

**Comment by TomW1605** [comment]
i think this actually worked then got broken. for a while my apprise.yaml only had the keys for discord in it but then i think a notification method got added and that broke it so it needed all of them. not exactly sure when it broke or if it was just using the default config when it was working and i then change it to use the broken one.

**Comment by 1337-server** [comment]
I suspect it may have been this commit https://github.com/1337-server/automatic-ripping-machine/commit/46577481f70b3a21ac07b343455a5f7ae1cf4702 that did it.

I changed the code to make it much smaller, but if one fails they all fail. I'll try to revert this change  today.

**Comment by 1337-server** [comment]
Code is now reverted and should be working again.

If not ping and ill reopen and look into it.
