### ISSUE TITLE
settings saving crashes if comment missing

### ISSUE THREAD

**Issue by TomW1605** [1337-server/automatic-ripping-machine#59]
if the comment for a setting is missing the settings page crashes when you save. it gives a key error here https://github.com/1337-server/automatic-ripping-machine/blob/3e5a391a042c1f2bfe07342c708bf96c04de927a/arm/ui/routes.py#L349

**Comment by 1337-server** [comment]
The whole setting page needs re-written to be static anyway. I hope to be able to get this done soon.

**Comment by 1337-server** [comment]
Closing as this should now be fixed.
