### ISSUE TITLE
[REQUEST] auto refresh ui

### ISSUE THREAD

**Issue by TomW1605** [1337-server/automatic-ripping-machine#6]
### Description
it would be great if the UI would auto refresh when a status changed

**Comment by TomW1605** [comment]
also the log contains lots more info on progress (eg eta) it would be great to get this into the ui

**Comment by 1337-server** [comment]
Both great ideas, ill look into these.

**Comment by TomW1605** [comment]
i do have plenty of experience in python and web development so let me know if you want me to take a look

**Comment by 1337-server** [comment]
If you're happy to work on them, what ever you could do would be a big help.

The latest version is the v2.4 branch it has some extra things that v2.3 doesnt have. If you could let me know if you start working on one of them so i can avoid touching it, that would be great.

**Comment by TomW1605** [comment]
ok im going to have a look at auto refreshing the job list and main ui

**Comment by 1337-server** [comment]
Closing as feature is now implemented. 

Thanks!
