### ISSUE TITLE
db issue

### ISSUE THREAD

**Issue by cpesko** [1337-server/automatic-ripping-machine#62]
[THE_SEVENTH_DAY_161785554965.log](https://github.com/1337-server/automatic-ripping-machine/files/6276111/THE_SEVENTH_DAY_161785554965.log)

Hey 1337 There must be something up with database this is the seventh day but pulling scraper blade.

**Comment by 1337-server** [comment]
Great catch, This is a problem with the previous jobs checker.

The function expects a unique crc64 but if all previous entries have 'None' set then it will not work correctly. This should now be fixed with the latest commit.
