### ISSUE TITLE
missing file on the wiki, config, .abcde.conf page

### ISSUE THREAD

**Issue by emmakat** [1337-server/automatic-ripping-machine#68]
On https://github.com/1337-server/automatic-ripping-machine/wiki/.abcde.conf
The file mentioned at the bottom of the page "You can view the full file here .abcde.conf" goes to https://github.com/1337-server/automatic-ripping-machine/blob/2.2_dev/setup/.abcde.conf which gives a 404 error 
I can't seem to submit a PR for this but I think it's meant to point to https://github.com/1337-server/automatic-ripping-machine/blob/v2_devel/setup/.abcde.conf ?

**Comment by 1337-server** [comment]
Updated. Thanks for pointing it out.
