### ISSUE TITLE
something wrong on insert.

### ISSUE THREAD

**Issue by cpesko** [1337-server/automatic-ripping-machine#69]
Apr 12 02:10:44 zero systemd[1]: Removed slice User Slice of UID 1001.
Apr 12 02:10:48 zero python3[1647]: [2021-04-12 02:10:48,386] DEBUG in routes: joblist
Apr 12 02:10:48 zero python3[1647]: 10.0.0.45 - - [12/Apr/2021 02:10:48] "#033[37mGET /json?mode=joblist HTTP/1.1#033[0m" 200 -
Apr 12 02:10:52 zero kernel: [74398.547850] ata6.00: failed to read SCR 1 (Emask=0x40)
Apr 12 02:10:52 zero kernel: [74398.547854] ata6.01: failed to read SCR 1 (Emask=0x40)
Apr 12 02:10:52 zero kernel: [74398.547856] ata6.02: failed to read SCR 1 (Emask=0x40)
Apr 12 02:10:52 zero kernel: [74398.547859] ata6.02: failed to read SCR 0 (Emask=0x40)
Apr 12 02:10:52 zero kernel: [74398.547861] ata6.03: failed to read SCR 1 (Emask=0x40)
Apr 12 02:10:52 zero kernel: [74398.547863] ata6.03: failed to read SCR 0 (Emask=0x40)
Apr 12 02:10:52 zero kernel: [74398.547864] ata6.04: failed to read SCR 1 (Emask=0x40)
Apr 12 02:10:53 zero kernel: [74399.023772] ata6.15: SATA link up 1.5 Gbps (SStatus 113 SControl 310)
Apr 12 02:10:53 zero python3[1647]: [2021-04-12 02:10:53,379] DEBUG in routes: joblist
Apr 12 02:10:53 zero python3[1647]: 10.0.0.45 - - [12/Apr/2021 02:10:53] "#033[37mGET /json?mode=joblist HTTP/1.1#033[0m" 200 -
Apr 12 02:10:53 zero kernel: [74399.338247] ata6.00: SATA link down (SStatus 0 SControl 310)
Apr 12 02:10:53 zero kernel: [74399.654367] ata6.01: SATA link down (SStatus 0 SControl 310)
Apr 12 02:10:54 zero kernel: [74399.969832] ahci 0000:04:00.0: FBS is disabled
Apr 12 02:10:54 zero kernel: [74400.131721] ahci 0000:04:00.0: FBS is enabled
Apr 12 02:10:54 zero kernel: [74400.132685] ata6.02: SATA link up 1.5 Gbps (SStatus 113 SControl 310)
Apr 12 02:10:54 zero kernel: [74400.445905] ahci 0000:04:00.0: FBS is disabled
Apr 12 02:10:54 zero kernel: [74400.607684] ahci 0000:04:00.0: FBS is enabled
Apr 12 02:10:54 zero kernel: [74400.608577] ata6.03: SATA link up 1.5 Gbps (SStatus 113 SControl 310)
Apr 12 02:10:55 zero kernel: [74400.921680] ata6.04: SATA link down (SStatus 0 SControl 310)
Apr 12 02:10:55 zero kernel: [74400.922915] ata6.02: configured for PIO0
Apr 12 02:10:55 zero kernel: [74400.925276] ata6.03: configured for UDMA/33
Apr 12 02:10:58 zero kernel: [74404.161088] sr 5:3:0:0: [sr3] tag#13 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Apr 12 02:10:58 zero kernel: [74404.161093] sr 5:3:0:0: [sr3] tag#13 Sense Key : Illegal Request [current] 
Apr 12 02:10:58 zero kernel: [74404.161098] sr 5:3:0:0: [sr3] tag#13 Add. Sense: Read of scrambled sector without authentication
Apr 12 02:10:58 zero kernel: [74404.161102] sr 5:3:0:0: [sr3] tag#13 CDB: Read(10) 28 00 00 3e 9f 80 00 00 40 00
Apr 12 02:10:58 zero kernel: [74404.161106] blk_update_request: I/O error, dev sr3, sector 16416256 op 0x0:(READ) flags 0x80700 phys_seg 12 prio class 0
Apr 12 02:10:58 zero python3[1647]: [2021-04-12 02:10:58,386] DEBUG in routes: joblist
Apr 12 02:10:58 zero python3[1647]: 10.0.0.45 - - [12/Apr/2021 02:10:58] "#033[37mGET /json?mode=joblist HTTP/1.1#033[0m" 200 -
Apr 12 02:10:58 zero kernel: [74404.265108] sr 5:3:0:0: [sr3] tag#15 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Apr 12 02:10:58 zero kernel: [74404.265112] sr 5:3:0:0: [sr3] tag#15 Sense Key : Illegal Request [current] 
Apr 12 02:10:58 zero kernel: [74404.265117] sr 5:3:0:0: [sr3] tag#15 Add. Sense: Read of scrambled sector without authentication
Apr 12 02:10:58 zero kernel: [74404.265120] sr 5:3:0:0: [sr3] tag#15 CDB: Read(10) 28 00 00 3e 9f 81 00 00 01 00
Apr 12 02:10:58 zero kernel: [74404.265123] blk_update_request: I/O error, dev sr3, sector 16416260 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
Apr 12 02:10:58 zero kernel: [74404.266881] Buffer I/O error on dev sr3, logical block 4104065, async page read
Apr 12 02:11:03 zero python3[1647]: [2021-04-12 02:11:03,380] DEBUG in routes: joblist
Apr 12 02:11:03 zero python3[1647]: 10.0.0.45 - - [12/Apr/2021 02:11:03] "#033[37mGET /json?mode=joblist HTTP/1.1#033[0m" 200 -
Apr 12 02:11:03 zero ARM: [ARM] Starting ARM on sr3
Apr 12 02:11:03 zero systemd[1]: Created slice User Slice of UID 1001.
Apr 12 02:11:03 zero systemd[1]: Starting User Runtime Directory /run/user/1001...
Apr 12 02:11:03 zero systemd[1]: Finished User Runtime Directory /run/user/1001.
Apr 12 02:11:03 zero systemd[1]: Starting User Manager for UID 1001...
Apr 12 02:11:03 zero systemd[50404]: Reached target Paths.
Apr 12 02:11:03 zero systemd[50404]: Reached target Timers.
Apr 12 02:11:03 zero systemd[50404]: Starting D-Bus User Message Bus Socket.
Apr 12 02:11:03 zero systemd[50404]: Listening on GnuPG network certificate management daemon.
Apr 12 02:11:03 zero systemd[50404]: Listening on GnuPG cryptographic agent and passphrase cache (access for web browsers).
Apr 12 02:11:03 zero systemd[50404]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
Apr 12 02:11:03 zero systemd[50404]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Apr 12 02:11:03 zero systemd[50404]: Listening on GnuPG cryptographic agent and passphrase cache.
Apr 12 02:11:03 zero systemd[50404]: Listening on debconf communication socket.
Apr 12 02:11:03 zero systemd[50404]: Listening on REST API socket for snapd user session agent.
Apr 12 02:11:03 zero systemd[50404]: Listening on D-Bus User Message Bus Socket.
Apr 12 02:11:03 zero systemd[50404]: Reached target Sockets.
Apr 12 02:11:03 zero systemd[50404]: Reached target Basic System.
Apr 12 02:11:03 zero systemd[50404]: Reached target Main User Target.
Apr 12 02:11:03 zero systemd[50404]: Startup finished in 251ms.
Apr 12 02:11:03 zero systemd[1]: Started User Manager for UID 1001.
Apr 12 02:11:03 zero systemd[1]: Started Session c73 of user arm.
Apr 12 02:11:03 zero systemd[1]: session-c73.scope: Succeeded.
Apr 12 02:11:03 zero ARM: [ARM] ARM Webgui running. 
Apr 12 02:11:05 zero postfix/pickup[46401]: 1E8D41E3B1D: uid=1001 from=<arm>

**Comment by cpesko** [comment]
2 02:35:50 zero python3[52503]: [2021-04-12 02:35:50,423] DEBUG in routes: joblist
Apr 12 02:35:50 zero python3[52503]: 10.0.0.45 - - [12/Apr/2021 02:35:50] "#033[37mGET /json?mode=joblist HTTP/1.1#033[0m" 200 -

Apr 12 02:35:53 zero kernel: [75899.665569] ata10.00: failed to read SCR 1 (Emask=0x40)
Apr 12 02:35:53 zero kernel: [75899.665573] ata10.01: failed to read SCR 1 (Emask=0x40)
Apr 12 02:35:53 zero kernel: [75899.665575] ata10.02: failed to read SCR 1 (Emask=0x40)
Apr 12 02:35:53 zero kernel: [75899.665578] ata10.02: failed to read SCR 0 (Emask=0x40)
Apr 12 02:35:53 zero kernel: [75899.665579] ata10.03: failed to read SCR 1 (Emask=0x40)
Apr 12 02:35:53 zero kernel: [75899.665581] ata10.03: failed to read SCR 0 (Emask=0x40)
Apr 12 02:35:53 zero kernel: [75899.665583] ata10.04: failed to read SCR 1 (Emask=0x40)
Apr 12 02:35:54 zero kernel: [75900.141545] ata10.15: SATA link up 1.5 Gbps (SStatus 113 SControl 310)
Apr 12 02:35:54 zero kernel: [75900.455722] ata10.00: SATA link down (SStatus 0 SControl 310)
Apr 12 02:35:54 zero kernel: [75900.772124] ata10.01: SATA link down (SStatus 0 SControl 310)
Apr 12 02:35:55 zero kernel: [75901.087415] ahci 0000:06:00.0: FBS is disabled
Apr 12 02:35:55 zero python3[52503]: [2021-04-12 02:35:55,426] DEBUG in routes: joblist
Apr 12 02:35:55 zero python3[52503]: 10.0.0.45 - - [12/Apr/2021 02:35:55] "#033[37mGET /json?mode=joblist HTTP/1.1#033[0m" 200 -
Apr 12 02:35:55 zero kernel: [75901.249494] ahci 0000:06:00.0: FBS is enabled
Apr 12 02:35:55 zero kernel: [75901.250324] ata10.02: SATA link up 1.5 Gbps (SStatus 113 SControl 310)
Apr 12 02:35:55 zero kernel: [75901.563545] ahci 0000:06:00.0: FBS is disabled
Apr 12 02:35:55 zero kernel: [75901.725447] ahci 0000:06:00.0: FBS is enabled
Apr 12 02:35:55 zero kernel: [75901.726313] ata10.03: SATA link up 1.5 Gbps (SStatus 113 SControl 310)
Apr 12 02:35:56 zero kernel: [75902.043636] ata10.04: SATA link down (SStatus 0 SControl 310)
Apr 12 02:35:56 zero kernel: [75902.048370] ata10.02: configured for UDMA/33
Apr 12 02:35:56 zero multipathd[1127]: pktcdvd5: unusable path (wild) - checker failed
Apr 12 02:35:56 zero kernel: [75902.053452] ata10.03: configured for UDMA/33
Apr 12 02:35:56 zero kernel: [75902.054138] pktcdvd: pktcdvd6: pkt_get_last_written failed
Apr 12 02:36:00 zero python3[52503]: [2021-04-12 02:36:00,421] DEBUG in routes: joblist
Apr 12 02:36:00 zero python3[52503]: 10.0.0.45 - - [12/Apr/2021 02:36:00] "#033[37mGET /json?mode=joblist HTTP/1.1#033[0m" 200 -
Apr 12 02:36:05 zero python3[52503]: [2021-04-12 02:36:05,425] DEBUG in routes: joblist
Apr 12 02:36:05 zero python3[52503]: 10.0.0.45 - - [12/Apr/2021 02:36:05] "#033[37mGET /json?mode=joblist HTTP/1.1#033[0m" 200 -
Apr 12 02:36:10 zero python3[52503]: [2021-04-12 02:36:10,427] DEBUG in routes: joblist
Apr 12 02:36:10 zero python3[52503]: 10.0.0.45 - - [12/Apr/2021 02:36:10] "#033[37mGET /json?mode=joblist HTTP/1.1#033[0m" 200 -
Apr 12 02:36:13 zero ARM: [ARM] Starting ARM on sr0
Apr 12 02:36:13 zero systemd[1]: Created slice User Slice of UID 1001.
Apr 12 02:36:13 zero systemd[1]: Starting User Runtime Directory /run/user/1001...
Apr 12 02:36:13 zero systemd[1]: Finished User Runtime Directory /run/user/1001.
Apr 12 02:36:13 zero systemd[1]: Starting User Manager for UID 1001...
Apr 12 02:36:13 zero systemd[53199]: Reached target Paths.
Apr 12 02:36:13 zero systemd[53199]: Reached target Timers.
Apr 12 02:36:13 zero systemd[53199]: Starting D-Bus User Message Bus Socket.
Apr 12 02:36:13 zero systemd[53199]: Listening on GnuPG network certificate management daemon.
Apr 12 02:36:13 zero systemd[53199]: Listening on GnuPG cryptographic agent and passphrase cache (access for web browsers).
Apr 12 02:36:13 zero systemd[53199]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
Apr 12 02:36:13 zero systemd[53199]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Apr 12 02:36:13 zero systemd[53199]: Listening on GnuPG cryptographic agent and passphrase cache.
Apr 12 02:36:13 zero systemd[53199]: Listening on debconf communication socket.
Apr 12 02:36:13 zero systemd[53199]: Listening on REST API socket for snapd user session agent.
Apr 12 02:36:13 zero systemd[53199]: Listening on D-Bus User Message Bus Socket.
Apr 12 02:36:13 zero systemd[53199]: Reached target Sockets.
Apr 12 02:36:13 zero systemd[53199]: Reached target Basic System.
Apr 12 02:36:13 zero systemd[53199]: Reached target Main User Target.
Apr 12 02:36:13 zero systemd[53199]: Startup finished in 243ms.
Apr 12 02:36:13 zero systemd[1]: Started User Manager for UID 1001.
Apr 12 02:36:13 zero systemd[1]: Started Session c90 of user arm.
Apr 12 02:36:13 zero systemd[1]: session-c90.scope: Succeeded.
Apr 12 02:36:13 zero ARM: [ARM] ARM Webgui running. 
Apr 12 02:36:15 zero python3[52503]: [2021-04-12 02:36:15,421] DEBUG in routes: joblist
Apr 12 02:36:15 zero python3[52503]: 10.0.0.45 - - [12/Apr/2021 02:36:15] "#033[37mGET /json?mode=joblist HTTP/1.1#033[0m" 200 -
Apr 12 02:36:20 zero python3[52503]: [2021-04-12 02:36:20,424] DEBUG in routes: joblist
Apr 12 02:36:20 zero python3[52503]: 10.0.0.45 - - [12/Apr/2021 02:36:20] "#033[37mGET /json?mode=joblist HTTP/1.1#033[0m" 200 -
Apr 12 02:36:22 zero kernel: [75928.036304] ata3: SATA link up 1.5 Gbps (SStatus 113 SControl 300)
Apr 12 02:36:22 zero kernel: [75928.037815] ata3.00: configured for UDMA/33
Apr 12 02:36:23 zero systemd[1]: Stopping User Manager for UID 1001...
Apr 12 02:36:23 zero systemd[53199]: Stopped target Main User Target.
Apr 12 02:36:23 zero systemd[53199]: Stopped target Basic System.
Apr 12 02:36:23 zero systemd[53199]: Stopped target Paths.
Apr 12 02:36:23 zero systemd[53199]: Stopped target Sockets.
Apr 12 02:36:23 zero systemd[53199]: Stopped target Timers.
Apr 12 02:36:23 zero systemd[53199]: dbus.socket: Succeeded.
Apr 12 02:36:23 zero systemd[53199]: Closed D-Bus User Message Bus Socket.
Apr 12 02:36:23 zero systemd[53199]: dirmngr.socket: Succeeded.
Apr 12 02:36:23 zero systemd[53199]: Closed GnuPG network certificate management daemon.
Apr 12 02:36:23 zero systemd[53199]: gpg-agent-browser.socket: Succeeded.
Apr 12 02:36:23 zero systemd[53199]: Closed GnuPG cryptographic agent and passphrase cache (access for web browsers).
Apr 12 02:36:23 zero systemd[53199]: gpg-agent-extra.socket: Succeeded.
Apr 12 02:36:23 zero systemd[53199]: Closed GnuPG cryptographic agent and passphrase cache (restricted).
Apr 12 02:36:23 zero systemd[53199]: gpg-agent-ssh.socket: Succeeded.
Apr 12 02:36:23 zero systemd[53199]: Closed GnuPG cryptographic agent (ssh-agent emulation).
Apr 12 02:36:23 zero systemd[53199]: gpg-agent.socket: Succeeded.
Apr 12 02:36:23 zero systemd[53199]: Closed GnuPG cryptographic agent and passphrase cache.
Apr 12 02:36:23 zero systemd[53199]: pk-debconf-helper.socket: Succeeded.
Apr 12 02:36:23 zero systemd[53199]: Closed debconf communication socket.
Apr 12 02:36:23 zero systemd[53199]: snapd.session-agent.socket: Succeeded.
Apr 12 02:36:23 zero systemd[53199]: Closed REST API socket for snapd user session agent.
Apr 12 02:36:23 zero systemd[53199]: Reached target Shutdown.
Apr 12 02:36:23 zero systemd[53199]: systemd-exit.service: Succeeded.
Apr 12 02:36:23 zero systemd[53199]: Finished Exit the Session.
Apr 12 02:36:23 zero systemd[53199]: Reached target Exit the Session.
Apr 12 02:36:23 zero systemd[1]: user@1001.service: Succeeded.
Apr 12 02:36:23 zero systemd[1]: Stopped User Manager for UID 1001.
Apr 12 02:36:23 zero systemd[1]: Stopping User Runtime Directory /run/user/1001...
Apr 12 02:36:23 zero systemd[43199]: run-user-1001.mount: Succeeded.
Apr 12 02:36:23 zero systemd[1]: run-user-1001.mount: Succeeded.
Apr 12 02:36:23 zero systemd[1]: user-runtime-dir@1001.service: Succeeded.
Apr 12 02:36:23 zero systemd[1]: Stopped User Runtime Directory /run/user/1001.
Apr 12 02:36:23 zero systemd[1]: Removed slice User Slice of UID 1001.
Apr 12 02:36:23 zero kernel: [75929.417053] sr 2:0:0:0: [sr0] tag#20 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Apr 12 02:36:23 zero kernel: [75929.417058] sr 2:0:0:0: [sr0] tag#20 Sense Key : Illegal Request [current] 
Apr 12 02:36:23 zero kernel: [75929.417063] sr 2:0:0:0: [sr0] tag#20 Add. Sense: Read of scrambled sector without authentication
Apr 12 02:36:23 zero kernel: [75929.417067] sr 2:0:0:0: [sr0] tag#20 CDB: Read(10) 28 00 00 20 af 00 00 00 40 00
Apr 12 02:36:23 zero kernel: [75929.417071] blk_update_request: I/O error, dev sr0, sector 8567808 op 0x0:(READ) flags 0x80700 phys_seg 9 prio class 0
Apr 12 02:36:23 zero kernel: [75929.497002] sr 2:0:0:0: [sr0] tag#21 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
Apr 12 02:36:23 zero kernel: [75929.497006] sr 2:0:0:0: [sr0] tag#21 Sense Key : Illegal Request [current] 
Apr 12 02:36:23 zero kernel: [75929.497010] sr 2:0:0:0: [sr0] tag#21 Add. Sense: Read of scrambled sector without authentication
Apr 12 02:36:23 zero kernel: [75929.497014] sr 2:0:0:0: [sr0] tag#21 CDB: Read(10) 28 00 00 20 af 00 00 00 01 00
Apr 12 02:36:23 zero kernel: [75929.497017] blk_update_request: I/O error, dev sr0, sector 8567808 op 0x0:(READ) flags 0x0 phys_seg 1 prio class 0
Apr 12 02:36:23 zero kernel: [75929.498469] Buffer I/O error on dev sr0, logical block 2141952, async page read
Apr 12 02:36:25 zero python3[52503]: [2021-04-12 02:36:25,425] DEBUG in routes: joblist
Apr 12 02:36:25 zero python3[52503]: 10.0.0.45 - - [12/Apr/2021 02:36:25] "#033[37mGET /json?mode=joblist HTTP/1.1#033[0m" 200 -
Apr 12 02:36:28 zero ARM: [ARM] Starting ARM on sr0
Apr 12 02:36:28 zero systemd[1]: Created slice User Slice of UID 1001.
Apr 12 02:36:28 zero systemd[1]: Starting User Runtime Directory /run/user/1001...
Apr 12 02:36:28 zero systemd[1]: Finished User Runtime Directory /run/user/1001.
Apr 12 02:36:28 zero systemd[1]: Starting User Manager for UID 1001...
Apr 12 02:36:29 zero systemd[53264]: Reached target Paths.
Apr 12 02:36:29 zero systemd[53264]: Reached target Timers.
Apr 12 02:36:29 zero systemd[53264]: Starting D-Bus User Message Bus Socket.
Apr 12 02:36:29 zero systemd[53264]: Listening on GnuPG network certificate management daemon.
Apr 12 02:36:29 zero systemd[53264]: Listening on GnuPG cryptographic agent and passphrase cache (access for web browsers).
Apr 12 02:36:29 zero systemd[53264]: Listening on GnuPG cryptographic agent and passphrase cache (restricted).
Apr 12 02:36:29 zero systemd[53264]: Listening on GnuPG cryptographic agent (ssh-agent emulation).
Apr 12 02:36:29 zero systemd[53264]: Listening on GnuPG cryptographic agent and passphrase cache.
Apr 12 02:36:29 zero systemd[53264]: Listening on debconf communication socket.
Apr 12 02:36:29 zero systemd[53264]: Listening on REST API socket for snapd user session agent.
Apr 12 02:36:29 zero systemd[53264]: Listening on D-Bus User Message Bus Socket.
Apr 12 02:36:29 zero systemd[53264]: Reached target Sockets.
Apr 12 02:36:29 zero systemd[53264]: Reached target Basic System.
Apr 12 02:36:29 zero systemd[53264]: Reached target Main User Target.
Apr 12 02:36:29 zero systemd[53264]: Startup finished in 250ms.
Apr 12 02:36:29 zero systemd[1]: Started User Manager for UID 1001.
Apr 12 02:36:29 zero systemd[1]: Started Session c91 of user arm.
Apr 12 02:36:29 zero systemd[1]: session-c91.scope: Succeeded.
Apr 12 02:36:29 zero ARM: [ARM] ARM Webgui running. 
Apr 12 02:36:30 zero postfix/pickup[46401]: 4725A1E3B1D: uid=1001 from=<arm>

Apr 12 02:36:30 zero python3[52503]: [2021-04-12 02:36:30,424] DEBUG in routes: joblist
Apr 12 02:36:30 zero python3[52503]: 10.0.0.45 - - [12/Apr/2021 02:36:30] "#033[37mGET /json?mode=joblist HTTP/1.1#033[0m" 200 -
Apr 12 02:36:35 zero python3[52503]: [2021-04-12 02:36:35,424] DEBUG in routes: joblist
Apr 12 02:36:35 zero python3[52503]: 10.0.0.45 - - [12/Apr/2021 02:36:35] "#033[37mGET /json?mode=joblist HTTP/1.1#033[0m" 200 -
Apr 12 02:36:38 zero python3[52503]: [2021-04-12 02:36:38,183] DEBUG in utils: Head is: 6dfe7244b18e
Apr 12 02:36:38 zero python3[52503]: [2021-04-12 02:36:38,183] DEBUG in utils: Database version is: 6dfe7244b18e
Apr 12 02:36:38 zero python3[52503]: [2021-04-12 02:36:38,184] INFO in utils: Database is up to date
Apr 12 02:36:38 zero python3[52503]: 10.0.0.45 - - [12/Apr/2021 02:36:38] "#033[37mGET /index.html HTTP/1.1#033[0m" 200 -
Apr 12 02:36:38 zero python3[52503]: [2021-04-12 02:36:38,341] DEBUG in routes: joblist
Apr 12 02:36:38 zero python3[52503]: 10.0.0.45 - - [12/Apr/2021 02:36:38] "#033[37mGET /json?mode=joblist HTTP/1.1#033[0m" 200 -
Apr 12 02:36:38 zero kernel: [75944.480487] ata7: softreset failed (1st FIS failed)
Apr 12 02:36:39 zero systemd[1]: Stopping User Manager for UID 1001...
Apr 12 02:36:39 zero systemd[53264]: Stopped target Main User Target.
Apr 12 02:36:39 zero systemd[53264]: Stopped target Basic System.
Apr 12 02:36:39 zero systemd[53264]: Stopped target Paths.
Apr 12 02:36:39 zero systemd[53264]: Stopped target Sockets.
Apr 12 02:36:39 zero systemd[53264]: Stopped target Timers.
Apr 12 02:36:39 zero systemd[53264]: dbus.socket: Succeeded.
Apr 12 02:36:39 zero systemd[53264]: Closed D-Bus User Message Bus Socket.
Apr 12 02:36:39 zero systemd[53264]: dirmngr.socket: Succeeded.
Apr 12 02:36:39 zero systemd[53264]: Closed GnuPG network certificate management daemon.
Apr 12 02:36:39 zero systemd[53264]: gpg-agent-browser.socket: Succeeded.
Apr 12 02:36:39 zero systemd[53264]: Closed GnuPG cryptographic agent and passphrase cache (access for web browsers).
Apr 12 02:36:39 zero systemd[53264]: gpg-agent-extra.socket: Succeeded.
Apr 12 02:36:39 zero systemd[53264]: Closed GnuPG cryptographic agent and passphrase cache (restricted).
Apr 12 02:36:39 zero systemd[53264]: gpg-agent-ssh.socket: Succeeded.
Apr 12 02:36:39 zero systemd[53264]: Closed GnuPG cryptographic agent (ssh-agent emulation).
Apr 12 02:36:39 zero systemd[53264]: gpg-agent.socket: Succeeded.
Apr 12 02:36:39 zero systemd[53264]: Closed GnuPG cryptographic agent and passphrase cache.
Apr 12 02:36:39 zero systemd[53264]: pk-debconf-helper.socket: Succeeded.
Apr 12 02:36:39 zero systemd[53264]: Closed debconf communication socket.
Apr 12 02:36:39 zero systemd[53264]: snapd.session-agent.socket: Succeeded.
Apr 12 02:36:39 zero systemd[53264]: Closed REST API socket for snapd user session agent.
Apr 12 02:36:39 zero systemd[53264]: Reached target Shutdown.
Apr 12 02:36:39 zero systemd[53264]: systemd-exit.service: Succeeded.
Apr 12 02:36:39 zero systemd[53264]: Finished Exit the Session.
Apr 12 02:36:39 zero systemd[53264]: Reached target Exit the Session.
Apr 12 02:36:39 zero systemd[1]: user@1001.service: Succeeded.
Apr 12 02:36:39 zero systemd[1]: Stopped User Manager for UID 1001.
Apr 12 02:36:39 zero systemd[1]: Stopping User Runtime Directory /run/user/1001...
Apr 12 02:36:39 zero systemd[43199]: run-user-1001.mount: Succeeded.
Apr 12 02:36:39 zero systemd[1]: run-user-1001.mount: Succeeded.
Apr 12 02:36:39 zero systemd[1]: user-runtime-dir@1001.service: Succeeded.
Apr 12 02:36:39 zero systemd[1]: Stopped User Runtime Directory /run/user/1001.
Apr 12 02:36:39 zero systemd[1]: Removed slice User Slice of UID 1001.
Apr 12 02:36:43 zero python3[52503]: [2021-04-12 02:36:43,337] DEBUG in routes: joblist
Apr 12 02:36:43 zero python3[52503]: 10.0.0.45 - - [12/Apr/2021 02:36:43] "#033[37mGET /json?mode=joblist HTTP/1.1#033[0m" 200 -
Apr 12 02:36:48 zero python3[52503]: [2021-04-12 02:36:48,343] DEBUG in routes: joblist
Apr 12 02:36:48 zero python3[52503]: 10.0.0.45 - - [12/Apr/2021 02:36:48] "#033[37mGET /json?mode=joblist HTTP/1.1#033[0m" 200 -
Apr 12 02:36:48 zero kernel: [75954.479627] ata7: softreset failed (1st FIS failed)
Apr 12 02:36:53 zero python3[52503]: [2021-04-12 02:36:53,341] DEBUG in routes: joblist
Apr 12 02:36:53 zero python3[52503]: 10.0.0.45 - - [12/Apr/2021 02:36:53] "#033[37mGET /json?mode=joblist HTTP/1.1#033[0m" 200 -

**Comment by cpesko** [comment]
but when I run main.py with python its working...

**Comment by 1337-server** [comment]
Can you check/setup postfix to see if you get any error messages from it ?

It looks like its trying to send something.
```
Apr 12 02:36:30 zero postfix/pickup[46401]: 4725A1E3B1D: uid=1001 from=
Apr 12 02:36:38 zero kernel: [75944.480487] ata7: softreset failed (1st FIS failed)
```

**Comment by cpesko** [comment]
?

**Comment by cpesko** [comment]
ok figured it out. arm.db arm wasnt owner...
