### ISSUE TITLE
No docs for creating a user on the docker container

### ISSUE THREAD

**Issue by shitwolfymakes** [1337-server/automatic-ripping-machine#71]
### Description
I have just installed and set everything up according to [this](https://github.com/1337-server/automatic-ripping-machine/wiki/docker), and am trying to interact with the website.

Site appears correctly, but mostly every page prompts me to log in. I can't seem to find any documentation on what the default credentials are, or how to create a user account.

### Environment
Ubuntu 20.04.2 LTS, running in VMWare ESXi 6.7

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]

**Comment by 1337-server** [comment]
Apologies the final step is omitted.

You need to visit /setup to create the admin account.

**Comment by shitwolfymakes** [comment]
When I do that I get redirected to index, and the following messages appear:

`Successfully created all of the ARM directories`
`Setup of the database was successful.`
`[Errno 13] Permission denied: '/opt/arm/installed'`

`/opt/arm/installed` does not exist, even though I had already done `sudo chmod -R 777 /opt`. When is list the directory, all folders are listed with 777 permissions.

**Comment by 1337-server** [comment]
That error can be ignored when using docker.

You should now be able to create an admin account by visiting any other page that's not / 

There are no default values for login, it should ask you to create an admin account.

**Comment by shitwolfymakes** [comment]
That works, thanks! I'll close this when the wiki gets updated to reflect that

**Comment by 1337-server** [comment]
Wiki updated to include this info

**Comment by gingerbeardman** [comment]
It would be great if the final steps of the /setup were on the docker page

https://hub.docker.com/r/1337server/automatic-ripping-machine

cheers!

**Comment by shitwolfymakes** [comment]
It is: https://github.com/1337-server/automatic-ripping-machine

**Comment by gingerbeardman** [comment]
It's not at the docker hub link I posted above

**Comment by shitwolfymakes** [comment]
Ah, fair

**Comment by 1337-server** [comment]
> It isn't at the docker hub link I posted above

I've added this info to docker hub.

**Comment by gingerbeardman** [comment]
Thank you.
