### ISSUE TITLE
[Docker] Nothing happens after inserting disk

### ISSUE THREAD

**Issue by shitwolfymakes** [1337-server/automatic-ripping-machine#72]
### Description
The server I set this up on has 2 disk drives, I have confirmed they show up as `sr0` and `sr1`. When I insert a disk, nothing happens. The webapp works fine and I can properly edit the settings.

When I run `tail -f /var/log/syslog | grep ARM` I get:
```
Apr 21 00:43:25 arm ARM: Entering docker wrapper
Apr 21 00:43:25 arm ARM: No ID_s
Apr 21 00:43:25 arm ARM: xxx
Apr 21 00:43:45 arm ARM: Entering docker wrapper
Apr 21 00:43:45 arm ARM: /opt/arm/scripts/docker_arm_wrapper.sh xxx1 sr0
Apr 21 00:43:45 arm ARM: xxx3
Apr 21 00:43:45 arm ARM: fixing devname
```

Nothing at all happens when I open or insert a disk in drive 2 (sr1)

Nothing happens after it reaches "fixing devname". Per the [wiki](https://github.com/1337-server/automatic-ripping-machine/wiki/Docker-Troubleshooting) (which seems to have either a typo or a missing section when it talks about udev), I have updated and restarted udev. Then I rebooted, same thing.

I have setup the drives in the fstab:
```
/dev/sr0 /mnt/dev/sr0 udf,iso9660 users,noauto,exec,utf8 0 0
/dev/sr1 /mnt/dev/sr1 udf,iso9660 users,noauto,exec,utf8 0 0
```

And accounted for both devices in the docker command:
```
docker run -d \
   -p "8080:8080" \
   -e UID="1000" -e GID="1000" \
   -v "/home/arm:/home/arm" \
   -v "/mnt/media/ARM/Music:/home/arm/Music" \
   -v "/home/arm/config:/home/arm/config" \
   -v "/mnt/media/ARM/logs:/home/arm/logs" \
   -v "/mnt/media/ARM:/home/arm/media" \
   --device="/dev/sr0:/dev/sr0" \
   --device="/dev/sr1:/dev/sr1" \
   --privileged \
   --restart "always" \
   --name "arm-rippers" \
   1337server/automatic-ripping-machine:latest
```

My nfs share is properly mounting to `/mnt/media`, so I do not believe it is the cause of the problem.

### Environment
Ubuntu 20.04.2 LTS, running in VMWare ESXi 6.7

### Log file
None. Also, here is no documentation on how to manually rip when using the Docker setup.

**Comment by 1337-server** [comment]
what's the output of `lsscsi -g` ?

**Comment by shitwolfymakes** [comment]
Output:
```
[2:0:0:0]    cd/dvd NECVMWar VMware SATA CD00 1.00   /dev/sr0   /dev/sg0
[3:0:0:0]    cd/dvd NECVMWar VMware SATA CD00 1.00   /dev/sr1   /dev/sg1
[32:0:0:0]  disk      VMware      Virtual disk                2.0    /dev/sda   /dev/sg2
```

**Comment by 1337-server** [comment]
Really odd behaviour, does the arm user have access to the cdrom group ?

The original error message means it can't find the device `/dev/srx` so it assumes that it was given `srx` and tries to add `/dev` 
The only thing i think it could be is a permission issue.

**Comment by shitwolfymakes** [comment]
I only created one user (`arm`) when I installed the OS. I have confirmed that `arm` is the only member of cdrom using
`getent group cdrom`

Why is it looking for `srx` and not `sr0` or `sr1`? That first error always happens only when I open the dvd tray, so I believe that's normal behaviour. The comments in the [udev rule](https://github.com/1337-server/automatic-ripping-machine/blob/docker/setup/docker-arm.rules) seem to support that

Do I copy that command exactly, or is there a way to get the DVD label?

**Comment by 1337-server** [comment]
It does look for `sr0` and `sr1`. I meant that the x in `srx` would be replaced with an int for each drive you have. So if the udev triggers for sr0 it will look for sr0, etc.

You can get the label from udev, you can see how arm should be getting this info from here .

https://github.com/1337-server/automatic-ripping-machine/blob/3d7db077f1eec5d8ace1134e50398d62c81d911a/scripts/docker_arm_wrapper.sh#L103
You will also need the previous lines most likely from lines 98-106

But this isn't recommended as its not fixing what ever issue you're currently having. And as this happens with both the docker and the main ARM installs this might be your own setup. I'm not familiar with ESXi 6.7, so i can't really be of much help when trying to debug your setup.

Let me know if you need any more info

**Comment by shitwolfymakes** [comment]
I think I figured out where the script is breaking.

https://github.com/1337-server/automatic-ripping-machine/blob/3d7db077f1eec5d8ace1134e50398d62c81d911a/scripts/docker_arm_wrapper.sh#L128

If I add `echo $container_status | logger -t ARM -s` to line 129, it doesn't print anything. Line 128 does not appear to run, or store a value.

**Comment by shitwolfymakes** [comment]
I think I figured out where the script is breaking.

https://github.com/1337-server/automatic-ripping-machine/blob/3d7db077f1eec5d8ace1134e50398d62c81d911a/scripts/docker_arm_wrapper.sh#L128

If I add `echo $container_status | logger -t ARM -s` to line 129, it doesn't print anything. Line 128 does not appear to run, or store a value. Is it failing silently?

**Comment by 1337-server** [comment]
Is it possible your arm user doesn't have access to the docker group ? That may cause issues, but i'm not sure.

**Comment by shitwolfymakes** [comment]
Huh. Weird. Despite this install (Ubuntu Server 20.04) having been installed with the docker snap, I get `usermod: group 'docker' does not exist` when I run `sudo usermod -a -G docker arm`. Will look into this.

**Comment by shitwolfymakes** [comment]
Found an answer [here](https://askubuntu.com/questions/907110/docker-snap-cannot-connect-to-the-docker-daemon-is-the-docker-daemon-running-o), looks like docker installation via snap is not creating a docker user group

**Comment by shitwolfymakes** [comment]
Group created and user added. Same thing happens. The script is 777. 

I have determined without a doubt that the command: 
`docker container ls -l -f name="${CONTAINER_NAME}" --format '{{json .Status}}'` is either not being run by the script, or returning nothing. This behavior only occurs when these commands are run by the script. Running from the command line successfully returns the status info of the "arm-rippers" container. I have also confirmed that the CONTAINER_NAME is properly set and properly populating within the script.

Code:
```
echo "aaa1" | logger -t ARM -s
echo "$(docker container ls -l -f name="${CONTAINER_NAME}" --format '{{json .Status}}')" | logger -t ARM -s
echo "aaa2" | logger -t ARM -s
container_status="$(docker container ls -l -f name="${CONTAINER_NAME}" --format '{{json .Status}}')" | logger -t ARM -s
echo $container_status | logger -t ARM -s
echo "aaa3" | logger -t ARM -s
```

output:
```
aaa1
aaa2
```

**Comment by 1337-server** [comment]
You could depending on your use case, remove the check for the container running at all.

If you're running the container all the time you can safely remove the check 

```
# start ARM container, if not running, for WebUI
container_status="$(docker container ls -l -f name="${CONTAINER_NAME}" --format '{{json .Status}}')"
case "${container_status//\"}" in
  Up*)
    echo "container '${CONTAINER_NAME}' status: ${container_status}" | logger -t ARM
    ;;
  Exited*)
    startArmContainer
    ;;
  *)
    runArmContainer
    ;;
esac
```
And then the script will assume the container is always up and running. This leave a huge chunk of unused code, but that shouldn't cause any issues.

If the container isn't running all the time, and you want the script to start or create the container you will need to dig deeper into this.  `docker container ls -l -f name="${CONTAINER_NAME}" --format '{{json .Status}}')` needs to be working for creating or starting stopped containers.

**Comment by shitwolfymakes** [comment]
That works, but then it breaks on the next docker command in `startArmRip`. Only the docker commands are breaking

**Comment by 1337-server** [comment]
If even docker exec isn't working then you probably have a permission issue with docker. 

Do the docker exec commands work when you trigger them from a terminal ?

**Comment by shitwolfymakes** [comment]
Docker operates as expected when being used from the terminal. could it be an issue with whatever "user" process the udev rule calls the wrapper script from?

**Comment by 1337-server** [comment]
Thats what i was thinking, but ill be honest and say I'm not that experienced with docker or ESXi so i didnt want to point you in the wrong direction.

But my first thought that what ever user you have triggering the docker_wrapper doesn't have access to the docker group ? Maybe echo the current user when it runs and then check the `groups` of that user ?

**Comment by shitwolfymakes** [comment]
I totally get that. ESXi is a hypervisor and completely invisible to the OS, so unless Ubuntu wasn't mounting the drives, ESXi isn't a factor. Docker itself isn't broken so at this point it has to be either A) a permissions issue buried in here somewhere, or B) an issue caused by Ubuntu Server 20.04 not coming with something that Ubuntu Desktop 20.04 normally does.

I'm gonna try that next. Once I get this working I'm writing up a tutorial so no one has to deal with figuring all this out again.

**Comment by shitwolfymakes** [comment]
As befitting the massive pain in the ass this has been, the issue was caused by Snap. Apparently snap sets up services under itself, rather than under systemd, so a snap-installed docker doesn't appear when running `sudo systemctl status docker`. Uninstalling the snap and installing docker via the website fixed the problem. 

To be clear: DO NOT INSTALL DOCKER VIA SNAP

I'm going to try and script this out, then see if it's working with both drives.

**Comment by shitwolfymakes** [comment]
Got a preliminary script done, and it's working. The bigger problem for me is that the docker version does not see the second drive, only the first. It looks like the udev rule is not firing for drive 2 at all.

**Comment by 1337-server** [comment]
Did you do `sudo mkdir -p /mnt/dev/sr1` and a second fstab entry for it ?

**Comment by shitwolfymakes** [comment]
Okay, I physically swapped the drives in the case. Now that it's done, the udev rule fires when I put a disk in `sr1`, and doesn't fire for `sr0`. This appears to be a hardware driver issue with my LG WH16NS60 dvd drive. 

I'll try a physical repair, but at this point I'd say that this is confirmed working for multiple drives. Which pisses me off because this is the exact drive the original blog post suggests, and that's why I got it.

I'll work on a tutorial for this once I deal with that.

**Comment by 1337-server** [comment]
If you're trying to get UHD you may need to follow the firmware flashing guide provided by MakeMKV [here](https://forum.makemkv.com/forum/viewtopic.php?f=16&t=19634) 

The drive you have requires you to flash the firmware to unlock UHD ripping and even 4 years later (from the original blog post) its still one of the top recommended drives for ARM/MakeMKV

**Comment by shitwolfymakes** [comment]
Nope, I was testing that drive with a copy of Snatch (2000). Definitely not a UHD issue

Hmm. `sr1` is trying to run, but seems to hang or crash after logging `disk is a dvd`. It doesn't throw an error in `get_cdrom_status`, so I don't think it's breaking until at least here:
https://github.com/1337-server/automatic-ripping-machine/blob/3d7db077f1eec5d8ace1134e50398d62c81d911a/arm/ripper/main.py#L493

I've confirmed this happening with multiple dvds

**Comment by 1337-server** [comment]
Are there any error if you run the docker exec manually ?

**Comment by shitwolfymakes** [comment]
Not sure what you mean by that. Calling the wrapper script outside the rule always returns the NO_ID outcome, regardless of whether or not it's mounted

**Comment by shitwolfymakes** [comment]
Hold on. I might be looking at the the wrong branch. The docker container is built from the `docker` branch, right?

**Comment by 1337-server** [comment]
Yes the pre-built docker image is automatically built from the docker branch. It builds a fresh image every time the docker branch receives a new push/commit.

**Comment by shitwolfymakes** [comment]
Okay, I was reading through the default branch. How do I start it manually for the docker?

**Comment by 1337-server** [comment]
docker exec -i \
    -u "1000" \
    "arm-rippers" \
    python3 /opt/arm/arm/ripper/main.py \
      -d /dev/sr0 -t ID_CDROM_MEDIA_DVD=1 -l ID_FS_LABEL=MY_DVD_LABEL \
    | logger -t ARM
    
This will trigger a rip inside the docker.

**Comment by shitwolfymakes** [comment]
Ah. It was a permissions error. Need to make a note to run `chmod -R 775 /home/arm` after the setup creates all of the folders. Or else the app won't have write permissions.

Another good idea would be to redirect python's `STDERR` to the logger, so that we can see an errors via `tail -f /var/sys/syslog | grep ARM`, rather than having to run it manually. Should be an easy addition in the logger setup.

**Comment by shitwolfymakes** [comment]
Is there a discord or irc where people chat about this in real-time?

**Comment by 1337-server** [comment]
Glad you got it sorted! Ill look into pushing out errors to the host system.

As for discord/irc - Not currently, I did think about creating a discord for ARM but I'm not part of the ARM org or group so i didn't think it was appropriate for me to create one, and i didn't want to step on anyone's toes.

**Comment by shitwolfymakes** [comment]
I don't think you need to push errors in the container out. All you should need to do is tell python to write stderr to logger.error. [This](https://stackoverflow.com/questions/19425736/how-to-redirect-stdout-and-stderr-to-logger-in-python) may help.

Okay, I made a channel in my server to chat about this outside of endless issue threads. Add me on discord "wolfy#4577", and I'll send you an invite. It doesn't have to be official or anything, but the original repo is pretty dead in terms of actual development and we need a way to communicate.

**Comment by 1337-server** [comment]
Ill look into that, and Ill add on discord later today.

**Comment by 1337-server** [comment]
Issue seems to be resolved. Ill close this but ping if it needs re-opened
