### ISSUE TITLE
[Docker] All blu-rays are being named the same as the first blu-ray ripped

### ISSUE THREAD

**Issue by shitwolfymakes** [1337-server/automatic-ripping-machine#75]
### Description
Like the title says, after the first blu-ray, Darkest Hour, completed ripping and ejected, I repeated it with a few more blu-rays, in the following order:

1. Darkest Hour (2017)
2. A Beautiful Day in the Neighborhood (2019)
3. Dunkirk (2017)
4. Dunkirk Bonus Features
5. Bridge of Spies (2015)

Darkest Hour was originally titled "DARKESTHOUR_UPB75", and that is what the title appeared as when I inserted Beautiful Day, before I manually fixed the title and year of Darkest Hour via the UI. From there on, unless I manually corrected the titles within the default 60 seconds, every blu-ray I enter is populating with `title: Darkest Hour` and `year: 2017`. Then it is titleing the output folder with the incorrect name and year, which is failing jobs because I don't allow duplicates. 

NOTE: This behavior is only occurring when I insert blu-rays. Regular DVDs are populating title and year normally. I ripped my DVD of Enron: The Smartest Guys in the Room between blu-rays 1 and 2, and it ripped normally with the title as "ENRON".

I have attached the arm logs for all movies mentioned. 5 shows that if I manually retitle it in time, ARM works properly. It's pretty clear that the variable that stores the title of the blu-rays or a db call isn't get getting flushed properly, so that should give a pretty good idea of where the problem is occurring.

EDIT: And I just noticed this as I write this. Now that Bridge of Spies is finished ripping, it has started transcoding while Dunkirk is still transcoding. I have `MAX_CONCURRENT_TRANSCODES` set to 0, so ARM is not honoring that setting for blu-rays at the least, testing with a DVD right now.

### Environment
Ubuntu Server 20.04.02 LTS
ARM Docker 1337-server/automatic-ripping-machine:latest (before you accepted my PR yesterday, but that PR has no bearing on this issue)

### Log files
[1 - DARKESTHOUR_UPB75.log](https://github.com/1337-server/automatic-ripping-machine/files/6395248/1.-.DARKESTHOUR_UPB75.log)
[2 - BEAUTIFUL_DAY_IN_NEIGHBORHOOD.log](https://github.com/1337-server/automatic-ripping-machine/files/6395250/2.-.BEAUTIFUL_DAY_IN_NEIGHBORHOOD.log)
[3 - DUNKIRK_161964373458.log](https://github.com/1337-server/automatic-ripping-machine/files/6395251/3.-.DUNKIRK_161964373458.log)
[4 - DUNKIRK_BONUS.log](https://github.com/1337-server/automatic-ripping-machine/files/6395253/4.-.DUNKIRK_BONUS.log)
[5 - BRIDGE_OF_SPIES.log](https://github.com/1337-server/automatic-ripping-machine/files/6395254/5.-.BRIDGE_OF_SPIES.log)
[ENRON.log](https://github.com/1337-server/automatic-ripping-machine/files/6395256/ENRON.log)

**Comment by 1337-server** [comment]
Can you enable DEBUG mode ? It will show far more details. I suspect this is because with Blu-ray ARM never searches online database's for title information. It trusts the embedded information provided by the disc. I also think that its sticking around and not resetting or unloading the info. 

Hopefully the debug logs will narrow things down

**Comment by shitwolfymakes** [comment]
How do I do that? What do I need to add to the exec command?

**Comment by 1337-server** [comment]
No you change loglevel to `LOGLEVEL: "DEBUG"`

**Comment by shitwolfymakes** [comment]
Here you go. It doesn't log the duplicate directory it finds, so I created #76 to fix that.

[DUNKIRK_BONUS_161971453604.log](https://github.com/1337-server/automatic-ripping-machine/files/6401382/DUNKIRK_BONUS_161971453604.log)

**Comment by 1337-server** [comment]
I think latest build (once it finishes) should fix this issue.

The problem is that ARM can't get the crcid of the disc and it uses that to match other jobs (it defaults to None). And since your previous jobs all have crcid's of None then arm thinks they are they same and uses the info from the very first job it finds.

**Comment by shitwolfymakes** [comment]
Okay, I'll test it in a bit. I wasn't sure if this was a runtime bug that would reset after a reboot of the container, hence why I haven't done this yet￼

**Comment by shitwolfymakes** [comment]
Interesting. I stuck the blu-ray in and it works properly now, but for some reason it started a second rip. Of the same dvd, and it looks like it wasn't honoring the no duplicates policy.

Also, every job I try to click on (including old ones) is giving me type errors: `TypeError: 'NoneType' object does not support item assignment`

Is this due to updating the container? All I did was stop, delete, pull latest, and run

**Comment by shitwolfymakes** [comment]
I've confirmed that this is fixed the problem.

**Comment by 1337-server** [comment]
`MAX_CONCURRENT_TRANSCODES = 0` 

Disables the transcode limit. Is it only transcoding one at a time ?

**Comment by shitwolfymakes** [comment]
It is transcoding 2 at the same time, and will start a third transcode soon. It should only transcode 1 job at a time

**Comment by 1337-server** [comment]
Try setting it to 1

**Comment by shitwolfymakes** [comment]
The current transcodes are still going, but it looks like the current rip is paused.

**Comment by shitwolfymakes** [comment]
Okay, per our Discord chat, Saving changes to ARM settings freezes all active rips. I'll start a separate discussion issue for that. 

Setting `MAX_CONCURRENT_TRANSCODES = 1` is what sets it to 1 transcode at a time. That solved my problem once the current jobs completed. I'll start a separate discussion issue for that as well.

Given that the original issue has been solved, I'm closing this issue. Thanks for the help!
