### ISSUE TITLE
[Docker] Modifying settings during operation

### ISSUE THREAD

**Issue by shitwolfymakes** [1337-server/automatic-ripping-machine#77]
### Description
Currently, saving settings in the Docker version of ARM results in the hanging of any jobs in the ripping phase, but leaves transcode-phase jobs running. Do address this, there are 2 ways to go:

1. Add a warning dialog telling the user that all active rips will be stopped, and asking the user if they are sure. If the user chooses to follow through, automatically abandon the current rips and restart. Basically the normal functionality.
2. Save the settings but do not restart the container. Instead, at each entry point for the various operations that use the settings, update those settings before entering. This is a small architecture change, and may add a bit of overhead in terms of Big-O depending on how efficient the YAML reading code is, but it doesn't require the user to restart the process of ripping and transcoding.

Personally, I think option two is better long term, but I'd love to hear your feedback. And some documentation on how to set up a development environment for working on this. Atm I'm not sure how best to do that, and I'd like to actually help beyond minor edits through github lmao

**Comment by 1337-server** [comment]
I did add a warning after our discord conversation.

The commit is here: https://github.com/1337-server/automatic-ripping-machine/commit/8c6620e109dab1c1b66734e5f37ab04461f0e035

It shows the warning as a temporary measure if there are any active jobs running, i agree that option 2 is a much better way to go about things. I just need to implement something to update the settings in the main.py when a new job is added.

As for the dev environment I personally use Pycharm as it lets me work over my network, and also has built in support for building/deploying the docker image locally without pushing/pulling to/from the repo. Makes for much faster testing of new features or trying to fix bugs.

I wasn't sure if a dev quick start guide was necessary for ARM docker. All i had to do was git clone the docker branch, then open the folder as a project and press run or the `>>` in the gutter after i opened the Dockerfile. I'll need to test this with other IDE's to see if it needs more work than that.
