### ISSUE TITLE
Rip does not start automatically when disk inserted

### ISSUE THREAD

**Issue by utzer** [1337-server/automatic-ripping-machine#78]
### Description
When I insert a disk the rip does not start automatically. I need to start it with "/usr/bin/python3 /opt/arm/arm/ripper/main.py -d sr0" as the arm user.

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

git log -1                                                               [git][arm/.][v2_develU]
commit 87e98df00c34d5f06b2efb267d1444135d302ee2 (HEAD -> v2_devel, origin/v2_devel, origin/HEAD)
Author: 1337-server <62730074+1337-server@users.noreply.github.com>
Date:   Sat May 1 21:14:35 2021 +0100

### Log file
I think this does not help, but I can provide some output of tail -f /var/log/syslog, but which would be helpful?

**Comment by 1337-server** [comment]
Is arm outputting anything to the syslog ?

**Comment by utzer** [comment]
> Is arm outputting anything to the syslog ?

I can send the output when I start the next DVD, is a "grep arm" OK?

**Comment by 1337-server** [comment]
grep arm wouldnt show if the script fails though.

Can you look for this inside the tail syslog

`sr0: Process '/opt/arm/scripts/arm_wrapper.sh sr0' failed with exit code 1`

If you're seeing that you need to make the arm_wrapper.sh executable

`sudo chmod +x /opt/arm/scripts/arm_wrapper.sh`

**Comment by utzer** [comment]
> sr0: Process '/opt/arm/scripts/arm_wrapper.sh sr0' failed with exit code 1

Yes I see this. 

> If you're seeing that you need to make the arm_wrapper.sh executable
> sudo chmod +x /opt/arm/scripts/arm_wrapper.sh

Did I miss this somewhere in the guide?

**Comment by 1337-server** [comment]
No this was my fault for not adding this. Sorry about that, wiki is now updated with this info.

**Comment by utzer** [comment]
> No this was my fault for not adding this. Sorry about that, wiki is now updated with this info.

No problem, I like when my questions help to improve. Thanks for this.

**Comment by utzer** [comment]
I am really sorry to use this issue again. 

I am looking for some easy to gather information, maybe some forum, some place to read examples how to set makemkv/handbrake for arm. 

One thing I try to figure out is why it often does not detect a Blueray as a Blueray and then down samples it to DVD resolution. Next step would be to understand how to use some multi channel FLAC for the audio of Blueray to have this more or less lossless. 
Also maybe would like to use X265, need to try to encode same disk as X264 and then as X265 and see if the size reduction is worth it. 

There is so many questions and so few information I am able to find, especially in regard of arm. Maybe I am just searching for the wrong key words.

**Comment by utzer** [comment]
Just an addtion for the detection, this is a blueray:
![Screenshot_2021-05-10_20-46-51](https://user-images.githubusercontent.com/8361662/117709145-e3514480-b1d0-11eb-9547-4cc8a3a841e7.png)
I am unable to change the false detection, so now it is ripping it again and I guess it will again be down sampled to the DVD preset.

**Comment by utzer** [comment]
@1337-server I will have to look in this in the next days. I was actually wondering/trying to find out if there is some setting to rip/convert the disk with the original resolution. I don't want to downscale or upscale it, just use the input resolution as the output resolution. 
I will try the -e X264 and -e X265 and see what the difference is, also these I have to try on my "old" TV from 7 years ago I think. 

I stumbled over the --audio-copy-mask mask as well, need to check that too. 

What is a good way to benchmark this, deselect "main title" and set the maximum duration to some low value so it will just rip the extras or one extra? 

I did not switch the branch or pull since the initial post. 

How does arm decided if it is a DVD or a Blu-ray? 

Will add logs, found this in one of them, I guess some package is missing from the install guide for ubuntu. 
```
bdj.c:565: libbluray-j2se-1.1.2.jar not found.
bdj.c:752: BD-J check: Failed to load libbluray.jar
bdj.c:565: libbluray-j2se-1.1.2.jar not found.
bdj.c:752: BD-J check: Failed to load libbluray.jar
```
[Movie1_162067192307.log](https://github.com/1337-server/automatic-ripping-machine/files/6461338/Movie1_162067192307.log)
[Movie1.log](https://github.com/1337-server/automatic-ripping-machine/files/6461339/Movie1.log)

Same Blu-ray twice, once ripped with the DVD preset and once with the manually selected Blu-ray preset. 

Thanks for the help.

**Comment by 1337-server** [comment]
I think with handbrake you can set cropping to 0 (although i have never used this) and save it as a preset and then you can use that for ARM.

Personally for testing transcoding i would exclude ARM entirely and test with one small file and the HandBrake command line (HandBrakeCLI --help) till i have everything to my liking.
HandBrake has some great docs [here](https://handbrake.fr/docs/en/latest/cli/command-line-reference.html)

ARM uses very simple methods to identify the disc, it checks for specific folders that should exist on specific types of media.
These are the lines of code that is used for disc identification
https://github.com/1337-server/automatic-ripping-machine/blob/7dcda92a84b834217ff0ce95afe9f4c2f090644c/arm/ripper/identify.py#L37
to
https://github.com/1337-server/automatic-ripping-machine/blob/7dcda92a84b834217ff0ce95afe9f4c2f090644c/arm/ripper/identify.py#L57

Those logs wont help as they are INFO logs, DEBUG logs show far more information for helping to track down bug or issues.
Can you change to DEBUG logging and rerun the rips ?
[How to change to DEBUG](https://github.com/1337-server/automatic-ripping-machine/wiki/General-Troubleshooting#changing-logging-to-debug-mode)

**Comment by utzer** [comment]
I changed the log level to Debug and will rerun the rip of that particular Blu-Ray.

**Comment by utzer** [comment]
> I think with handbrake you can set cropping to 0 (although i have never used this) and save it as a preset and then you can use that for ARM.

I played with the cropping too, I thought it might be nice to crop the video, especially some of the older DVDs that still are 4:3 aspect ratio, here it would be nice to crop them, because then you can set it to play stretched on many devices, which is nicer than having black bars left and right. (I think that was my train of thought here.)

> 
> Personally for testing transcoding i would exclude ARM entirely and test with one small file and the HandBrake command line (HandBrakeCLI --help) till i have everything to my liking.

Hmm yes, not a bad idea, so I need some file for testing. 

> HandBrake has some great docs [here](https://handbrake.fr/docs/en/latest/cli/command-line-reference.html)

I did read some things there as well. 

> I thought i would add, that you could use the GUI interface if you're more comfortable to get everything to your liking and then save/export the profile and you could then pass that into the ARM config.

Maybe not a bad idea to set up a preset there, as most guides I found are referring to the gui with screenshots. 

> 
> First ARM check the FS ID's here
> 
> https://github.com/1337-server/automatic-ripping-machine/blob/7dcda92a84b834217ff0ce95afe9f4c2f090644c/arm/models/models.py#L67
> 
> Then ARM uses very simple methods to identify the disc, it checks for specific folders that should exist on specific types of media.
> These are the lines of code that is used for disc identification
> 
> https://github.com/1337-server/automatic-ripping-machine/blob/7dcda92a84b834217ff0ce95afe9f4c2f090644c/arm/ripper/identify.py#L37
> 
> to
> 
> https://github.com/1337-server/automatic-ripping-machine/blob/7dcda92a84b834217ff0ce95afe9f4c2f090644c/arm/ripper/identify.py#L57
> 
> Those logs wont help as they are INFO logs, DEBUG logs show far more information for helping to track down bug or issues.
> Can you change to DEBUG logging and rerun the rips ?
> [How to change to DEBUG](https://github.com/1337-server/automatic-ripping-machine/wiki/General-Troubleshooting#changing-logging-to-debug-mode)

One more question, I think arm fails to cleanup the temporary folders for some reason, so I did that manually some days ago and removed loads of data from the ./media/transcode and ./media/raw folder. I think I saw some log entry that it failed to clean up, but don't remember where I saw that. 

Again would like to state that I really love the idea of arm, it is a great pieace of SW and I think I will use it in the future, I like the idea to be able to rip CDs and other disks automatically and headless, it is nice and easy once setup. I think I will at some point try to use a RaspberryPi4, I know it got some hardware encoder, so it should be ok to run handbrake on it, but not sure about it. I mean it will be slow, but I think fine for the occasional rip once in a while.

**Comment by utzer** [comment]
Now I am confused... it says blue ray but it shows in the override setting for the rip that it runs as DVD. Here is the beginning of the log, just started the process. 
[movie1.log](https://github.com/1337-server/automatic-ripping-machine/files/6489758/movie1.log)

**Comment by 1337-server** [comment]
I think the settings in the page `/changeparams?config_id=` is not showing correctly. It seems to be reverting to the default values and not the values for the currently job.

**Comment by 1337-server** [comment]
can you pull the latest commit to test ?

**Comment by utzer** [comment]
Alright, will do the pull, I actually didn't pull since the initial clone 2 or 3 weeks ago.

**Comment by 1337-server** [comment]
Yep `git pull` is all that is needed unless you have modified the files.
