### ISSUE TITLE
error updating database after IDing movie

### ISSUE THREAD

**Issue by TomW1605** [1337-server/automatic-ripping-machine#8]
### Description
there is an error updating the database after a movie is identifyed. it looks like the wrong arguments are being passed here: `File "/opt/arm/arm/ripper/identify.py", line 338`see end of log for more info

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[007_DAD_FEATURE_EN.log](https://github.com/1337-server/automatic-ripping-machine/files/5759125/007_DAD_FEATURE_EN.log)

**Comment by 1337-server** [comment]
This was part of the changes for v2.4, trying to address the database locked error. I didnt create the dict needed for database_updater() function

**Comment by TomW1605** [comment]
i thought there was something missing. i have commented it out for now
