### ISSUE TITLE
changeparams not displaying current job values

### ISSUE THREAD

**Issue by 1337-server** [1337-server/automatic-ripping-machine#80]
How does arm decided if it is a DVD or a Blu-ray? 

Will add logs, found this in one of them, I guess some package is missing from the install guide for ubuntu. 
```
bdj.c:565: libbluray-j2se-1.1.2.jar not found.
bdj.c:752: BD-J check: Failed to load libbluray.jar
bdj.c:565: libbluray-j2se-1.1.2.jar not found.
bdj.c:752: BD-J check: Failed to load libbluray.jar
```
[Movie1_162067192307.log](https://github.com/1337-server/automatic-ripping-machine/files/6461338/Movie1_162067192307.log)
[Movie1.log](https://github.com/1337-server/automatic-ripping-machine/files/6461339/Movie1.log)

Same Blu-ray twice, once ripped with the DVD preset and once with the manually selected Blu-ray preset. 

Thanks for the help.

_Originally posted by @utzer in https://github.com/1337-server/automatic-ripping-machine/issues/78#issuecomment-838982588_

**Comment by utzer** [comment]
Hmm you're right, mediainfo shows the resolution of the output being
```
Width                                    : 1 916 pixels
Height                                   : 800 pixels
```
So that is definitely not DVD. So it detects correctly but shows incorrect in the changeparams. Cool.

**Comment by 1337-server** [comment]
Closing this as i think this is now fixed. But please ping and let me know if its not and ill re-open.

**Comment by utzer** [comment]
> Will add logs, found this in one of them, I guess some package is missing from the install guide for ubuntu.

Do you know which package it is that contains the libbluray.jar?

**Comment by 1337-server** [comment]
Im believe that `libbluray2` is part of the MakeMKV but i cant remember for certain.

**Comment by utzer** [comment]
> Its part of HandBrake [HandBrake/HandBrake#874](https://github.com/HandBrake/HandBrake/issues/874)

Not here it seems. 
```
apt-file list handbrake-cli
handbrake-cli: /usr/bin/HandBrakeCLI      
handbrake-cli: /usr/share/doc/handbrake-cli/changelog.Debian.gz
handbrake-cli: /usr/share/doc/handbrake-cli/copyright
handbrake-cli: /usr/share/doc/handbrake-cli/examples/tst.aspect
handbrake-cli: /usr/share/man/man1/HandBrakeCLI.1.gz
```

Most likely I would say it is this one here:
```
apt-file list libbluray-bdj
libbluray-bdj: /usr/share/doc/libbluray-bdj/changelog.Debian.gz
libbluray-bdj: /usr/share/doc/libbluray-bdj/copyright
libbluray-bdj: /usr/share/java/libbluray-awt-j2se-1.2.0.jar
libbluray-bdj: /usr/share/java/libbluray-j2se-1.2.0.jar

```
