### ISSUE TITLE
Duplicate Task / Rip Loop

### ISSUE THREAD

**Issue by mneimeyer** [1337-server/automatic-ripping-machine#82]
- [X] I have checked the wiki
- [X] I have searched for similar issues

Just finished setting up ARM from this repo last night on Debian 10 with four drives. I noticed that the UI showed 5 tasks, one a duplicate of itself. I assumed this was a glitch. This morning I woke up to find that only one drive was waiting for a new disc. On checking it looks like the discs are repeatedly re-ripping themselves. I've looked through the logs and nothing is apparent to me what the cause is. The final output is "singular" so my completed folder only has 4 sets (one file+extras folder for each disc).

I realize this may be two different issues: "duplicate task at the same time" + "repeated re-ripping". My gut says probably not so one bug report.

I've attached all the logs created by ARM since I kicked off the rip last night.

Thanks in advance for any wisdom.

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
root@ripper:/etc/arm# lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)] 
root@ripper:/opt/arm# git branch
v2_devel
root@ripper:/opt/arm# git log -1
commit 506df0f80f7db9a042172578cc3191e29819fc47 (HEAD -> v2_devel, tag: v2.5.3, origin/v2_devel, origin/HEAD)
Author: 1337-server <sndspamfilter@gmail.com>
Date:   Sat Jul 10 23:11:13 2021 +0100

    Possible fix for #73

### Log file

[logs.zip](https://github.com/1337-server/automatic-ripping-machine/files/6950559/logs.zip)

**Comment by mneimeyer** [comment]
I have read the wiki. I was able to solve the duplicate tasks appearing for a single disk insertion by rewriting my arm_wrapper.sh (attached as .txt because... Github)

Fundamentally, it appears that the udev rule was matching multiple times for me.

This still leaves the issue of insert -> rip -> eject -> tray closes immediately -> rerip -> eject -> tray closes immediately -> repeat forever.

Thanks for any wisdom on that.

[arm_wrapper.txt](https://github.com/1337-server/automatic-ripping-machine/files/6953767/arm_wrapper.txt)

**Comment by 1337-server** [comment]
The modified arm_wrapper.sh looks great. I'll try testing this out over the coming days.


I have also been having the issue of eject auto reinserting the disc. But unfortunately I haven't found a solution yet.

**Comment by mneimeyer** [comment]
Well at least I know it isn't just me or my setup. Doing some research I found some kernel bugs from several years ago that imply that this happens when ejecting drives which had been mounted. IE perhaps not *quite* unmounted at the time of eject.

I'm not a Python programmer but I was considering attempting to modify the eject function in arm/models/models.py to include a few loops around os.path.ismount which SEEMS like the logical way to test if the drive is still mounted. Placing that between the umount and the eject seems logical but again, not a Python programmer by training... so if that sparks thought in your brain and you get it working I'd defer to your implementation. I did try adding a time.sleep there and it didn't help at all.

Lastly, I did notice that in arm_wrapper.txt that I forgot to edit the "Starting ARM for..." line for Bluray and it still says "for CD".

**Comment by 1337-server** [comment]
I have played with time.sleep too but it didnt work. I may need to reimplement/revert to the previous method used in the main repo. Where are ARM does nothing if the disc is already previously ejected.

https://github.com/automatic-ripping-machine/automatic-ripping-machine/commit/87202a78ce6ca118e0133ec899e6a16b4ad046dc#diff-85b5f524d11ef5e52be9129a25182da4abc6086a436d0d8a4b5747344bc183d6

**Comment by mneimeyer** [comment]
Actually... Google finally came through. Along with some patience to actually read to the bottom of those decade old kernel bugs. Drop the attached file into /etc/sysctl.d, rename .txt to .conf and reboot OR run "sysctl -p"  and this seems to solve the eject->retract issue.

Also, FWIW, not really worth another report... I added a job.eject() to the line right before the except in the abandon_job function in /home/opt/arm/ui/utils.pu so when I abandon a job the disk is ejected as well.

[arm-uneject-fix.txt](https://github.com/1337-server/automatic-ripping-machine/files/6972823/arm-uneject-fix.txt)

**Comment by 1337-server** [comment]
Thats awesome! Thanks for looking into this.

If you want to submit a pull for the extra eject when abandoning and I can merge, if not i can add it. Just let me know.

**Comment by mneimeyer** [comment]
Was prepping a Pull Request that covers this and some other odds and ends. I notice you've done some work too. I've never made a pull request so I don't know if I should try to integrate the changes you've made since I forked or not.

Thanks in advance!

**Comment by 1337-server** [comment]
Appologies, i only noticed your changes after already updating this repo. They could have waited if i had known. I think it would probably be best to update your own fork, then submit the pull.
You should be able to easily update your own fork from this repo if i remember correctly there is a button on your forks "homepage", and then submit the pull with only minimal conflicts.

But if you're not able, just submit the pull and i can manage/fix the changes so they are all added. 

Some really awesome changes you've added!

**Comment by mneimeyer** [comment]
Will do. I just downloaded Ubuntu for another "child" ripper. I'm going to try and port my changes from the Debian install script to the Ubuntu one after work today. As soon as I do that I'll incorporate your changes and make the pull request. That should hopefully also catch any issues between Ubuntu 20 (the script) and Ubuntu 21 (current download) but I hope those aren't drastically different.

FWIW: My first "child" ripper was running Debian 11 so that appears to work fine as well.

Only.... ~450 more disks to go in my initial "let's rip my collection" run. :)

**Comment by 1337-server** [comment]
Ill close this now as the issue should be fixed with the latest commit.

If you dont mind me asking, how are you using the json notifications ?

**Comment by gingerbeardman** [comment]
> Actually... Google finally came through. Along with some patience to actually read to the bottom of those decade old kernel bugs. Drop the attached file into /etc/sysctl.d, rename .txt to .conf and reboot OR run "sysctl -p" and this seems to solve the eject->retract issue.
> 
> Also, FWIW, not really worth another report... I added a job.eject() to the line right before the except in the abandon_job function in /home/opt/arm/ui/utils.pu so when I abandon a job the disk is ejected as well.
> 
> [arm-uneject-fix.txt](https://github.com/1337-server/automatic-ripping-machine/files/6972823/arm-uneject-fix.txt)

On Synology the line `dev.cdrom.autoclose=0` should be added to `/etc/sysctl.conf`

Works a treat! Thank you.
