### ISSUE TITLE
Blueray always gets subtitle burned into video ínstead of activateable subtitle

### ISSUE THREAD

**Issue by utzer** [1337-server/automatic-ripping-machine#84]
- [x] I have checked the wiki
- [x] I have searched for similar issues

**Describe the bug**
Subtitles get burned into the MP4 file when ripping a Blue-ray, but not when ripping a DVD, the later one is desired. Subtitle for Blue-ray should be added as a optional to activate subtitle. 

**To Reproduce**
1. Rip a Blueray with this handbrake settings.
HB_ARGS_BD: 
```
--markers --audio-lang-list eng,deu,spa,fra --all-audio --audio-copy-mask aac,ac3,mp3,dts,dtshd --audio-fallback aac --subtitle-lang-list=eng,deu,spa,fra --first-subtitle --subtitle-burned=none --quality 24.0 --format av_mp4 --encoder-preset slower
```
I use almost the same settings for Handbrake in ARM when processing a DVD.
HB_ARGS_DVD: 
```
--markers --audio-lang-list eng,deu,spa,fra --all-audio --audio-copy-mask aac,ac3,mp3,dts,dtshd --audio-fallback aac --subtitle-lang-list=eng,deu,spa,fra --first-subtitle --subtitle-burned=none --quality 24.0 --format av_mp4 --encoder-preset veryslow
```

In a DVD when I play the MP4 with VLC I can activate a subtitle in the menu, in a BL it is fixed text in the video, it's not possible to activate another subtitle or deactivate the subtitle at all. 

It somehow looks like this Handbrake parameters are not working for the Blue-ray rip. I would be very happy if you can point me in the right direction to troubleshoot this. 

I also checked that /opt/arm is up-to-date and also the system is up to date. 

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

```

[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)] 
```
v2_devel
```

### Log file
[Run the rip in DEBUG and drag and drop the log file onto this comment box]

[>>>>> DRAG AND DROP LOG FILE HERE <<<<<]
[log.log](https://github.com/1337-server/automatic-ripping-machine/files/6960043/log.log)

**Comment by utzer** [comment]
OK, I did not find this info in the [docs](https://handbrake.fr/docs/en/1.3.0/advanced/subtitles.html), it reads

> **Bluray PGS Subtitles**
> With MP4, you can burn ONLY 1 subtitle track into the video.
> You can not pass-through PGS into MP4 as this file format does not support it.
> With MKV, you can pass-through multiple PGS tracks. These are not burned into the video unless you choose to do so however you can only burn 1 subtitle track into the file. The rest must be passed through.

So I only have to switch the container format to mkv I guess and that would solve it? The MKV container would still enclose the same H.264 with all the audio tracks and would additionally contain the subtitles?

**Comment by 1337-server** [comment]
> But it would still be H.264 in the container.

Yes



Did this solve your issue ?

**Comment by utzer** [comment]
> Did this solve your issue ?

Yes, thanks for your patience and sorry for self solving my issue. I got some reaction to it in the Fediverse, which actually steered me in the right direction and now I get .mp4 with mkv container and H.264 I guess.
