### ISSUE TITLE
Can't copy to network share ("invalid cross-device link")

### ISSUE THREAD

**Issue by charmarkk** [1337-server/automatic-ripping-machine#85]
- [X] I have checked the wiki
- [X] I have searched for similar issues

**Describe the bug**
When trying to have the output for my blu-ray backup be put onto my network share (via a raspi), I got an error of "invalid cross-device link." (FLCL.log) I haven't seen that one before, and oddly enough, it handled doing this same thing for the DVD (rod.log) I was backing up without a problem. 

I'm going to try with another blu-ray, but my machine doing this is pretty slow at it, so I thought that in th meantime I'd see if there's an easy fix or something I'm overlooking. Permissions on this particular share are open for any user (since it's also connected to my Windows machine). 

Update: Got the error again with another BD (LOTR Return of the King), but weirdly enough, it was indeed fully output onto my network drive, in all its 37GB glory.

**To Reproduce**
1. Rip a blu-ray
2. Set output for the completed files to be put on a network/Samba share (which is mounted onto the ARM machine via fstab). 
3. Profit?

### Environment
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"

ARM v. 2.2.0 dev 

### Log file
I also included the log for the DVD backup that completed and moved successfully (rod.log).

[FLCL.log](https://github.com/1337-server/automatic-ripping-machine/files/6965207/FLCL.2.log) <-- problem child
[rod.log](https://github.com/1337-server/automatic-ripping-machine/files/6965208/rod.log) <-- golden child
[LOTR_ROK.log](https://github.com/1337-server/automatic-ripping-machine/files/6971431/LOTR_ROK.log) <-- Trial 2

**Comment by 1337-server** [comment]
Sorry for not replying sooner, but i was looking into this. It seems that Python can have issues when dealing with files on different partitions. But this was mean to be resolved with shutil.move (which ARM uses)

Not sure why you are still experiancing this issue.

**Comment by charmarkk** [comment]
Curious, I wonder why it's working well with DVD files vs. BD ones! In any case, I wonder if I need a clean install of Ubuntu and ARM. I did pull from your repo here, but I wonder if I did it wrong or something (Git doesn't always click the right way in my head) so I don't have the proper updates or files. Either way, it's not a huge problem, just seemed like something I should report. 

Once I get around to fresh installs of everything, I can update again to see if it's working right. It doesn't seem terribly simple to work the ARM install "backwards."

**Comment by 1337-server** [comment]
It's maybe a size issue causing Python to run out of memory, or some other strangeness/bug that im not aware of. It seems odd that DVD's are fine but Blu-rays are causing issues.

I did create an uninstall bash script to make things easier for myself when testing. The reason i didn't share it is that it has no way of knowing if something was pre-installed before the ARM installation (git, wget, etc) and could break something else if its run without proper care/attention. 

I will post it later today when i have access to my dev system.

**Comment by charmarkk** [comment]
That sounds great! Thanks for all the help and continued work on this.

That'll be a big help. Linux and all I can understand, but git is like another creature to me. 🥲

**Comment by 1337-server** [comment]
I cant attach it because of github restrictions. but this is the file i use.

**arm-uninstall.sh**
```
sudo apt-get purge git -y
sudo add-apt-repository -r -y ppa:heyarje/makemkv-beta
sudo add-apt-repository -r -y ppa:stebbins/handbrake-releases

sudo add-apt-repository -r -y ppa:mc3man/xerus-media
sudo add-apt-repository -r -y ppa:mc3man/bionic-prop
sudo add-apt-repository -r -y ppa:mc3man/focal6
sudo apt update -y && \
sudo apt purge makemkv-bin makemkv-oss -y && \
sudo apt purge handbrake-cli libavcodec-extra -y && \
sudo apt purge abcde flac imagemagick glyrc cdparanoia -y && \
sudo apt purge at -y && \
sudo apt purge libcurl4-openssl-dev libssl-dev -y && \
sudo apt purge libdvd-pkg -y && \
sudo apt purge default-jre-headless -y
cd /opt/arm
sudo pip3 uninstall -y -r requirements.txt 
cd ~
sudo rm -R /opt/arm
sudo rm -R /home/arm
sudo rm -R /etc/arm/
sudo mkdir /etc/arm/
sudo rm -R /mnt/dev/sr0
sudo rm /etc/systemd/system/armui.service
sudo systemctl disable armui
sudo systemctl daemon-reload
```

**Comment by charmarkk** [comment]
So the uninstall script worked really well, thanks! Reinstall worked well (using the Ubuntu script) after having to manually remove some folders and users, but finally got it after a half hour.

Some of these problems might be that my last installation didn't upgrade the right way, probably my fault with Git. :)

Now, though, gnce I got to the "Setup the UI" stage, I was able to get to server/setup, but then after I set up the user, there's a bunch of errors being thrown. I have that file attached, only found something slightly related in #81. Will try a full reinstall later on, if the error traceback isn't fully conclusive.

[traceback.txt](https://github.com/1337-server/automatic-ripping-machine/files/7028003/traceback.txt)

**Comment by 1337-server** [comment]
This error means there was a problem updating the database. For some reason your database already has a job.stage column but your database has an old version number. 

You have a couple of options.

1. You would either need to manually edit the db to drop the job.stage and then insert a disc to trigger the db upgrade.
2. You could update the `alembic_version` table, changing the version_num to `c54d68996895`
3. Delete the db file and insert a disc to trigger arm to create a new db file with the correct entries. (this comes with the drawback of losing all previous ripped jobs and all history.)

You could use db browser for SQlite (use the normal version not the cipher) https://sqlitebrowser.org/ or any other program, this is just the one that i use.

**Comment by charmarkk** [comment]
No worries on the `mkdir`.

Both 1 and 3 did not work. 

Only 2 got the webserver page working. I have the newest YAML, so it wasn't anything to do with that.  I tried reinstalling, to the letter, twice, to see if I had done anything wrong, but it looks like the DB that is being generated when going to server/setup is prepopulating that incorrect version number. 

Seems I'm now fully updated and everything has access, it's working on a backup now. Back to the original issue - I'll set the output dir to the Pi folders and see if it throws the same error. Thanks for the continued help!

**Comment by 1337-server** [comment]
It was the hardcoded database version causing issues. Latest commit should fix the db issue.

Can you check the webui log for arm ?
It will provide much more details about the search history, and should point more clearly why its not finding a match.

**Comment by charmarkk** [comment]
1) I don't think I enabled the WebUI logs, I will do so with the next BD.

2) Glad I could discover the db bug for ya!

3) It just finished it's backup and it's moving things to the NAS, not yelling one bit about it. So that problem indeed seems solved! It was probably due to my wonky update installation from before.

Did you want me to open a new issue for the matching?

**Comment by 1337-server** [comment]
1. Did you do
``` 
sudo systemctl daemon-reload
sudo systemctl restart armui
```
after updating the service file ?

2. Thanks, i had completely forgotten that the db version is hardcoded for the armui setup. Its something that will need to be fix fully later.

3. Glad this seems to be fixed. Please update if this isnt.

Yes, if you wouldn't mind creating a new issue that would be great. It saves newer users from searching through large threads with lots of different issues in one thread.

**Comment by charmarkk** [comment]
This issue was solved by fully (and correctly) updating ARM to this repo's 2.5.5 version. Opening new issue for fuzzy matching.
