### ISSUE TITLE
Resolutions not as expected based on HB Preset Name

### ISSUE THREAD

**Issue by mneimeyer** [1337-server/automatic-ripping-machine#86]
- [X] I have checked the wiki
- [X] I have searched for similar issues

**Describe the bug**
A caveat, I expect this is most likely a bug in my understanding and not in ARM but I can't find any clear documentation either here or on the Handbrake site unless I've missed something. I'll be honest I'm not sure what terms I should be looking for. Thx

I set my HB_PRESET_DVD to "HQ 480p30 Surround" because DVDs are 480p. Checking the output of the first dozen or so Discs I've ripped it looks like this is forcing the output resolution to be constrained so that it is no larger than 720x480. I've got one that's 720x270 and one that's 686x480 and so on. No height is ever larger than 480 and no width is ever larger than 720. I had expected the video to always be 480 high and the width to vary based on whether the content was widescreen or fullscreen.

But if I bump up to 720p30 won't that scale up so that either the height is 720 or the width is 1280? With 480p source this feels wasteful of space.

Sorry for the confusion.

I have not started ripping Bluray so I assume the same question revolves around the 1080p30 presets as well.

Thanks in advance.

**Comment by 1337-server** [comment]
I believe with the built in presets its doesnt upscale unless you manually set the override, and wont use any extra space unless you force upscaling with the custom HB options in the arm.yaml.

So if the source is 480 (SD) but you choose the 720p30 handbrake doesnt actually upscale and doesnt use any extra space. At least that has been my own limited experiance with the built in presets. But take this with a grain of salt as i very rarely use the built in presets.

HandBrake states that it removes the black bars from some media as this saves space and speeds up encoding, that may be the reason for the showing of odd resolutions as those (720x270, 686x480) are not standard dvd sizes.

**Comment by 1337-server** [comment]
Closing as this seems to be resolved. Let me know if that's not the case and ill reopen.
