### ISSUE TITLE
Title by Title Progress for Multi-title DVD and Bluray - Task X of Y of Z

### ISSUE THREAD

**Issue by mneimeyer** [1337-server/automatic-ripping-machine#88]
**Describe the solution you'd like**
It looks like the progress displayed on the Home screen for DVDs and Blurays is the progress of one task which is one title. If a disc has multiple titles (such as special features) there is no indication of the progress down that list. I've been hit a couple times where "10 seconds left" turns into "30 minutes left" because it jumped to the next title.

**Describe alternatives you've considered**
I assume there's something that could be done to scrape the logs for total number of titles and then displaying "Title X of Y" above "Task # of #" but I can't figure it out. Especially not in Python. I'm also not sure how that would affect Data or CDs.

**Are you able to help code/implement this feature ?**
I don't think I can help but at the very least I'd be glad to beta test / debug once the heavy lifting is done.

**Additional**
The pull request I submitted included lsdvd as a requirement which has an option to output titles in Python format using the "-Oy" option. That format includes the length in seconds (thus easily comparable to the min/max duration configuration options). This might be an easier way to go than scraping logs but it doesn't work for Bluray.

https://github.com/beandog/bluray_info doesn't have Python output like lsdvd but it does have JSON output. I'm just not quite sure what I'm seeing. Apparently Bluray Playlists aren't the same as Titles???

That said, I compiled bluray_info as follows on my Debian box:

   apt install libbluray-dev
   cd /makeMKV/
   git clone https://github.com/beandog/bluray_info.git
   cd bluray_info/
   autoreconf -fi
   ./configure
   make && make install

Then a simple "bluray_info -j /dev/sr0" gave me a HUGE listing of "stuff" which my brain isn't following at all.

Thanks in advance!

**Comment by 1337-server** [comment]
This should be very simple to implement, as all you would need to do is add an additional scan for one of these lines

`handbrake.get_track_info Line found is: [00:27:35] scan: DVD has 16 title(s)`
`handbrake.handbrake_all Total number of tracks is 16`
`makemkv.get_track_info Found 3 titles`

MakeMKV/HandBrake both log how many tracks were found so, this should be really as simple as adding another re.search() with the correct regex here 

https://github.com/1337-server/automatic-ripping-machine/blob/541f6df9de4619c660ca14107078db60c52e4134/arm/ui/routes.py#L746


ARM currently doesnt track CDs progress in the ARMui (this is possible, it's just not something i have added yet.) 
Data discs would be slightly harder as there is no built in log to check for it.


Ill try to do some testing later today to try and add this.

**Comment by 1337-server** [comment]
Ive added a very simple version of this, but its not perfect. It doesnt account for items that ARM will skip.

So if it shows 32 items to rip but your settings mean you will only rip 15 items. It will still show the x/32 instead of x/15. If you can test and let me know if you run into any problems that would be great.

**Comment by mneimeyer** [comment]
I've ripped four discs now and it looks good to go!

**Comment by 1337-server** [comment]
Awesome, ill close this now as the feature is added.
