### ISSUE TITLE
Armui crashes

### ISSUE THREAD

**Issue by utzer** [1337-server/automatic-ripping-machine#90]
- [x] I have checked the wiki
- [ ] I have searched for similar issues

**Describe the bug**

systemctl status armui.service:
```
Aug 22 19:53:35 arm python3[2166]: Traceback (most recent call last):
Aug 22 19:53:35 arm python3[2166]:   File "/opt/arm/arm/runui.py", line 5, in <module>
Aug 22 19:53:35 arm python3[2166]:     from arm.ui import app  # noqa E402
Aug 22 19:53:35 arm python3[2166]:   File "/opt/arm/arm/../arm/ui/__init__.py", line 8, in <module>
Aug 22 19:53:35 arm python3[2166]:     from flask_cors import CORS
Aug 22 19:53:35 arm python3[2166]: ModuleNotFoundError: No module named 'flask_cors'
Aug 22 19:53:35 arm systemd[1]: armui.service: Main process exited, code=exited, status=1/FAILURE
```

**To Reproduce**
1. Boot computer

### Environment
[OS Distribution and version (run "cat /etc/lsb-release")]

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.2 LTS"
```

[ARM Release Version or if cloning from git branch/commit (run "git branch" and "git log -1" to get this)] 
```
v2_devel
```

Not sure what the problem is here. Arm UI crashed frequently. 

Is there some log I can check?

**Comment by utzer** [comment]
Hmm now it started, restart counter at 26.

**Comment by 1337-server** [comment]
You will need to run `pip3 install flask_cors` or `pip3 install flask-cors`

or you can run 
```cd /opt/arm/
pip3 install -r requirements.txt```

The latest version came with a new requirement to allow ARM to add sub servers to its ui.

**Comment by utzer** [comment]
Well... nobody told me that I had to run `pip3 install -r requirements.txt` after an update. 

So one step further. 

Now I get this on the arm webpage:
```
Traceback (most recent call last)

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2464, in __call__

    return self.wsgi_app(environ, start_response)

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2450, in wsgi_app

    response = self.handle_exception(e)

    File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function

    return cors_after_request(app.make_response(f(*args, **kwargs)))

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1867, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise

    raise value

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app

    response = self.full_dispatch_request()

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "/usr/local/lib/python3.8/dist-packages/flask_cors/extension.py", line 165, in wrapped_function

    return cors_after_request(app.make_response(f(*args, **kwargs)))

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception

    reraise(exc_type, exc_value, tb)

    File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise

    raise value

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request

    rv = self.dispatch_request()

    File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

    File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 272, in decorated_view

    return func(*args, **kwargs)

    File "/opt/arm/arm/ui/routes.py", line 708, in home

    if cfg['ARM_NAME'] != "":

    KeyError: 'ARM_NAME'

```

**Comment by utzer** [comment]
> pip3 install -r requirements.txt

yes, I figured that out, but seems still something is off...

**Comment by 1337-server** [comment]
Have a look at the changes to arm.yaml

https://github.com/1337-server/automatic-ripping-machine/blob/v2_devel/docs/arm.yaml.sample

Some new things are added, so you may need to either re-copy the arm.yaml from the docs folder. Or manually add the new items.
```
ARM_NAME: ""
ARM_CHILDREN: ""
PREVENT_99: true
JSON_URL: ""
NOTIFY_JOBID: false
```

**Comment by utzer** [comment]
alright, I added 
```
ARM_NAME: ""
ARM_CHILDREN: ""
PREVENT_99: true
JSON_URL: ""
NOTIFY_JOBID: false
```
It works. 

One unrelated question, what was the doubt point for using a RaspberryPi4, which software was not available for ARM? MakeMKV?

**Comment by 1337-server** [comment]
Fantastic, glad you got it sorted. 

I’m sure there are now software versions available for arm chips (rpi4, etc) for all of the programs that ARM uses. So it should be possible to now use a rpi. 

But for transcoding this would be painfully slow or may not work at all, unless you are just ripping the raw files.

**Comment by utzer** [comment]
Hmm yes, the PI4 has hardware encoders, so the hope was to use the right x264 preset and use that, would be cool if this was possible.

**Comment by utzer** [comment]
One last off topic question, is there a way to rip DVDs to HDD, then eject them and then transcode them?

**Comment by 1337-server** [comment]
Yes, you just need to use MakeMKV instead of handbrake for the ripping. 


In your arm.yaml change the mode from 'backup' to 'mkv' and make sure main feature is false. It should now rip all files to HDD and then start transcoding after the disc is ejected.

**Comment by utzer** [comment]
The explanation is really strange for this setting, for me it reads like "do not set mkv, it will fail on Blureay". 

````
# Method of MakeMKV to use for Blu Ray discs.  Options are "mkv" or "backup".
# backup decrypts the dvd and then copies it to the hard drive.  This allows HandBrake to apply some of it's
# analytical abilities such as the main-feature identification.  This method seems to offer success on bluray 
# discs that fail in "mkv" mode. *** NOTE: MakeMKV only supports the backup method on BluRay discs.  ARM does
# not use MakeMKV for DVDs.   
RIPMETHOD: "backup"
```

**Comment by 1337-server** [comment]
It's meant to mean that some Blu-ray discs can fail when using the 'mkv' method on Blu-rays. I haven't experienced this issue, so I can't comment on what failure is causes. But I always use 'mkv' as this allows me to rip DVD's to hard drive and continue when I'm doing large batches of discs.

```
*** NOTE: MakeMKV only supports the backup method on BluRay discs.  ARM does
# not use MakeMKV for DVDs.  
```
This part is no longer true

I'll try to update this when I get some free time.

I'll close this as the original issue has been resolved.

**Comment by utzer** [comment]
I have to set MAINFEATURE to true, otherwise it does not rip anything from DVDs, the main folder and the extras folder will be empty.
