### ISSUE TITLE
Cannot use "Created Time" to sort logs in WebUI

### ISSUE THREAD

**Issue by charmarkk** [1337-server/automatic-ripping-machine#92]
- [X] I have checked the wiki
- [X] I have searched for similar issues

**Describe the bug**
When using the WebUI, you can sort ascending or descending by Log File title or Size, but not by Created Time. When clicking on Created Time, it does seem to sort, but not in any coherent manner.

**To Reproduce**
1. Enter WebUI with some logs present.
2. Attempt to sort by Created Time. Then, attempt to sort by Name or Size. Observe differences in behavior.

### Environment
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"

ARM 2.5.5_dev

### Log file
I don't believe it's necessary for this particular issue.

**Comment by 1337-server** [comment]
Confirmed this. I'll start looking for alternatives as a dont think the version used by ARM is currently being worked on, so its unlikely that the problem will by fixed.

**Comment by 1337-server** [comment]
Apologies, I made a mistake when I looked into this. It does seem that the plugin is no longer being developed. But it's not really a bug, It's part of how it creates the dates from the Date() function. It seems to require dates in a specific format. 

For the sorting to work with dates you would need to change your arm.yaml config to have the date format month/day/year
```
# Allows you to format the date/time to your own liking
# This will be used throughout ARM and ARMui
DATE_FORMAT: "%m-%d-%Y %H:%M:%S"
```

I've updated the sample config to be the default option for new installations.
