### ISSUE TITLE
ARM will eject disc after rip and transcode, causing issues when sequencing jobs (ARM ejects discs twice)

### ISSUE THREAD

**Issue by charmarkk** [1337-server/automatic-ripping-machine#93]
- [X] I have checked the wiki
- [X] I have searched for similar issues

**Describe the bug**
It appears that ARM will signal to eject a disc twice. 

Rip the disc using ARM, skip the transcode and move the "finished" files to a network share for later encoding. 

After a rip successfully completes, a disc is ejected then the project is "transcoded." The transcoding is skipped on the ARM machine to make use of a more powerful computer elsewhere for BD projects. Once the "transcode" (file move) finishes, "processing" is complete, after which ARM again unmounts and ejects the disc. 

This is a problem because: I will rip the disc, which takes maybe 30 mins if all goes well, then plan to do the next right after. However, the file move - even over Ethernet - takes about 10 min but is ultimately unpredictable. So it is difficult to efficiently sequence and batch jobs using the same drive (I only have one BD capable drive at the moment).

**To Reproduce**
1. Set the output directory to be a networked or otherwise saving-delayed drive.
2. Rip a disc, electing to skip the transcode.
3. Once the ripping is complete, observe ARM Will then process the files. ARM signals to eject the disc and unmount the media. Now put it in your next disc to rip.
4. Observe that once the file saving is done, ARM will again send a command to unmount and eject.

Logs below to illustrate this. Die Another Day finished ripping (with errors but enough to finish the main title), then Tomorrow Never Dies was inserted into the BD drive. Once Die Another Day finished transferring, another eject command was sent, causing Tomorrow Never Dies to error out because the tray was opened.

### Environment
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"

ARM 2.5.5_dev

### Log file

Main issue (repetition of commands) can be found in Die Another Day's log, but results of this action (rip can't complete because tray is open) in Tomorrow Never Dies' log. 

[DIEANOTHERDAY.log](https://github.com/1337-server/automatic-ripping-machine/files/7042759/DIEANOTHERDAY.log)
[TOMORROW_NEVER_DIES.log](https://github.com/1337-server/automatic-ripping-machine/files/7042763/TOMORROW_NEVER_DIES.log)

**Comment by 1337-server** [comment]
Latest commit should fix this issue. This feature was previously in ARM already but was removed when trying to solve and eject issue. But should now be ok to re-add. Let me know if you encounter any problems.
