### ISSUE TITLE
No UDF Support - Documentation or Install Script???

### ISSUE THREAD

**Issue by mneimeyer** [1337-server/automatic-ripping-machine#97]
- [X] I have checked the wiki

**Describe the bug**
Testing on a newly installed system I was confused why ARM kept insisting DVDs were Data discs. Long story short I compiled my kernel without UDF support.

I'm not sure if this should be checked in the installation script(s), perhaps by parsing /proc/filesystems with the caveat that filesystems supported by loadable modules may not appear in that list OR if that should be a troubleshooting tip in the Wiki.

Both?

This may only be an issue for those who compile their kernels from scratch or use source based distros hence the question as to where this should be addressed.

Thanks!

P.S. ~200 DVDs down ~300 to go. Thanks!

**Comment by 1337-server** [comment]
I think this may be a good addition to the wiki, as I'm not sure how common it is to compile your own kernel.

But if it's relatively common, I'm happy to include checks for UDF support.

**Comment by 1337-server** [comment]
Warning now added to the wiki.
