### ISSUE TITLE
/

### ISSUE THREAD

**Issue by themoddedcube** [1337-server/automatic-ripping-machine#99]
/

**Comment by 1337-server** [comment]
You seem to be mapping outside the container to the same port as inside the container. But arm doesn't use 9090. It uses 8080.

Try mapping inside the container to 8080 and outside to the port you want.

**Comment by themoddedcube** [comment]
Yes I just fixed that, but for some reason my code and title got deleted from here...

**Comment by 1337-server** [comment]
Closing as I'm not sure what problem you are now having. Please update with more info if you are still having issues.
